### ISSUE TITLE
Use TravisCI to publish PyPI packages

### ISSUE THREAD

**Issue by Turbo87** [geoalchemy/geoalchemy2#101]
I'm doing this on my own projects too, and it works pretty well.

see http://www.agmweb.ca/2015-05-08-travis-pypi

@elemoine since the package on PyPI is registered to your account you would have to install this.

**Comment by Turbo87** [comment]
@elemoine any comments?

**Comment by elemoine** [comment]
Sounds very good. I'll look at it. Again, sorry for the delay responding.
