### ISSUE TITLE
Issue with geoalchemy2 and sqlalchemy 1.0.6

### ISSUE THREAD

**Issue by troytoman** [geoalchemy/geoalchemy2#106]
I have some code that works fine for sqlalchemy 0.9.3 but is breaking on 1.0.6. I'm not sure if it is a geoalchemy2 issue or a sqlalchemy issue - thought I would start here. 

I have a object that has an attribute defined as 
    geom = Column(geoalchemy2.Geometry('POLYGON'))

In the test code, I create a valid geometry for this attribute. But, then I want to test what happens if there is no geometry. So, I do the following:

image.geom = None
db.db_session.commit()

With geoalchemy2 0.2.4 and sqlalchemy 0.9.3 this works fine. But, with geoalchemy 0.2.4 and slqalchemy 1.0.6 I get the following trace:

/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py:150: in do
    return getattr(self.registry(), name)(*args, **kwargs)
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py:790: in commit
    self.transaction.commit()
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py:392: in commit
    self._prepare_impl()
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py:372: in _prepare_impl
    self.session.flush()
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py:2004: in flush
    self._flush(objects)
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py:2122: in _flush
    transaction.rollback(_capture_exception=True)
/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py:60: in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py:2086: in _flush
    flush_context.execute()
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py:373: in execute
    rec.execute(self)
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py:532: in execute
    uow
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py:170: in save_obj
    mapper, table, update)
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py:630: in _emit_update_statements
    lambda rec: (
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py:459: in _collect_update_commands
    value, state.committed_state[propkey]):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sqlalchemy.sql.elements.BinaryExpression object at 0x56141d0>

    def __bool__(self):
        if self.operator in (operator.eq, operator.ne):
            return self.operator(hash(self._orig[0]), hash(self._orig[1]))
        else:
>           raise TypeError("Boolean value of this clause is not defined")
E           TypeError: Boolean value of this clause is not defined

There was a similar sqlalchemy issue (https://bitbucket.org/zzzeek/sqlalchemy/issue/3402/new-stack-trace-when-combining-non-eq) that was supposedly fixed in 1.0.3

My question is:
- should I not ever be assigning geom = None?
- is there an issue with geoalchmeny2 and support for sqlalchemy 1.0?
- or does this look like a regression in sqlalchemy?

**Comment by troytoman** [comment]
This has been acknowledged as a sqlalchemy issue:

https://bitbucket.org/zzzeek/sqlalchemy/issue/3469/comparison-in-persistencepy-can-trip-up-on

a fix is in master and looks like it will be included in 1.0.7

**Comment by elemoine** [comment]
Thanks @troytoman!
