### ISSUE TITLE
_SpatialElement assumes bytestrings no unicode

### ISSUE THREAD

**Issue by tdamsma** [geoalchemy/geoalchemy2#108]
So the following code fails:

```
wkt = WKTElement('POLYGON((1 2,3 4))')
print(wkt)
```

while this is accepted:

```
wkt = WKTElement(b'POLYGON((1 2,3 4))')
print(wkt)
```

I feel that as it is possible to pass unicode strings to WKTElement it should be able to print them too

**Comment by elemoine** [comment]
I am not reproducing this issue.
