### ISSUE TITLE
Syntax error when using mysql

### ISSUE THREAD

**Issue by mwiebusch78** [geoalchemy/geoalchemy2#109]
I am using geoalchemy2 0.2.5, sqlalchemy 1.0.5, pymysql 0.6.6, and mysql 5.6.26. Copying the Lake class from the ORM tutorial and calling create_all() gives the following SQL syntax error:

sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(POLYGON,-1), \n\tPRIMARY KEY (id)\n)' at line 4") [SQL: '\nCREATE TABLE lake (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tname VARCHAR(255), \n\tgeom geometry(POLYGON,-1), \n\tPRIMARY KEY (id)\n)\n\n']

According to the mysql docs a column with spatial data should be created like this:

    CREATE TABLE geom (g GEOMETRY NOT NULL, SPATIAL INDEX(g)) ENGINE=MyISAM;

**Comment by tsauerwein** [comment]
GeoAlchemy 2 does not support MySQL, only PostgreSQL/PostGIS. [GeoAlchemy 1](https://github.com/geoalchemy/geoalchemy) supports MySQL though.

**Comment by mwiebusch78** [comment]
I now installed postgresql 9.4.4. I create the engine with

    create_engine('postgresql://myuser:mypasswd@localhost/mydb')

and creating/dropping ordinary tables works. However, for the code from the tutorial I still get an error:

sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) type "geometry" does not exist
LINE 5:  geom geometry(POLYGON,-1), 
              ^
 [SQL: '\nCREATE TABLE lake (\n\tid SERIAL NOT NULL, \n\tname VARCHAR(255), \n\tgeom geometry(POLYGON,-1), \n\tPRIMARY KEY (id)\n)\n\n']

**Comment by lexicalunit** [comment]
@tsauerwein: Is there no planned support for MySQL using GeoAlchemy2?

**Comment by tsauerwein** [comment]
@lexicalunit No sorry, it's not planned from our side, because we are mainly working with Postgres/PostGIS.

**Comment by mnbucher** [comment]
bypassed this by defining my own geometry class as follows:

```
from sqlalchemy import func
from sqlalchemy.types import UserDefinedType

class Geometry(UserDefinedType):
    def get_col_spec(self):
        return 'GEOMETRY'

    def bind_expression(self, bindvalue):
        return func.ST_GeomFromText(bindvalue, type_=self)

    def column_expression(self, col):
        return func.ST_AsText(col, type_=self)
```

and using it in the model:

```
location_coordinates = Column(Geometry, nullable=False)
```

**Comment by adrien-berchet** [comment]
Thanks for this update @mnbucher !
I am working on MySQL support in #330 so I will consider your snippet, though it's not really the way I want to solve this because we want to use the same type for any dialect. Btw, does it work to create / drop tables and columns, and to use extended WKT?

**Comment by mnbucher** [comment]
> Thanks for this update @mnbucher !
> I am working on MySQL support in #330 so I will consider your snippet, though it's not really the way I want to solve this because we want to use the same type for any dialect. Btw, does it work to create / drop tables and columns, and to use extended WKT?

@adrien-berchet ok thanks for the update! i don't use the ORM for creating tables but do it rather directly via an SQL script, so i haven't checked this. i just needed a quick way to store new items on the existing DB table (on MariaDB) with an additional point datatype and the code above seems to do the job!

**Comment by adrien-berchet** [comment]
Ok, thanks for these details!
