### ISSUE TITLE
Q: what are the recommended libraries for GIS-transformations to be used on client-side with GeoAlchemy?

### ISSUE THREAD

**Issue by vak** [geoalchemy/geoalchemy2#111]
Hi

Q: what are the recommended libraries for GIS-transformations and calculations to be used not on DB-side via SQL-queries, but on client-side with Python and GeoAlchemy2?

I went through the docs several times and I saw hints about shaply, but it doesn't seem to support, e.g. very important ST_Distance_Sphere.

**Comment by Turbo87** [comment]
PostGIS is using the [GEOS](http://trac.osgeo.org/geos/) library internally. Maybe you could use that too if you want to calculate stuff outside of PostGIS. GeoAlchemy2 only has basic support for shapely because everything else would be out of scope for this library.
