### ISSUE TITLE
[ask] qlalchemy.schema.CreateTable do not render corect datatype public.geography 

### ISSUE THREAD

**Issue by adamailru** [geoalchemy/geoalchemy2#116]
How can I render it as geo-dll compatible with psql ?

I have bellow code:

    from sqlalchemy.ext.declarative import declarative_base
    from sqlalchemy import Column
    from geoalchemy2.types import Geography

    class OrderMetadata(declarative_base()):    
        __tablename__ = "order_metadata"
        __table_args__ = {"schema": "taxi"} 
        end_point = Column("end_point", Geography)
        
        @classmethod
        def show_create_table(cls, connection, echo=True):
            engine = create_engine(connection, echo=echo)
            return CreateTable(cls.__table__, bind=engine)

When I execute, I recevie this dll:

    >>> print OrderMetadata.show_create_table(postgre) # doctest: +NORMALIZE_WHITESPACE
    CREATE TABLE taxi.order_metadata (    	
    	end_point geography(GEOMETRY,-1)
    )

When I try to use this on psql, I receive error:

    test_ada=# CREATE TABLE taxi.order_metadata (     
    test_ada(#     end_point geography(GEOMETRY,-1)
    test_ada(#     );
    ERROR:  type "geography" does not exist
    LINE 2:     end_point geography(GEOMETRY,-1)
                          ^
edit: actually it is created after, but i dont like to see error:

    test_ada=# \d+ taxi.order_metadata;
                                     Table "taxi.order_metadata"
        Column     |           Type           | Modifiers | Storage  | Stats target | Description 
    ---------------+--------------------------+-----------+----------+--------------+-------------
     end_point     | geography(Geometry,4326) |           | main     |              | 
    Has OIDs: no
But if I use postgre public.geography data type all looks ok:
        
    test_ada=# CREATE TABLE taxi.order_metadata (     
    test_ada(#         end_point public.geography
    test_ada(#         );
    CREATE TABLE
    
P.S. there is CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;  

How can I render it as geo-dll compatible with psql ?

**Comment by elemoine** [comment]
Sorry but I don't understand the question. PostGIS should be enabled in your database, with `CREATE EXTENSION postgis`. With PostGIS enabled, `OrderMetadata.__table__.create(engine)` should create the table as expected.

**Comment by elemoine** [comment]
Code that works for me:

```py
from sqlalchemy import Column, Integer
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from geoalchemy2 import Geography

Base = declarative_base()


class Test(Base):
    __tablename__ = 'test'
    gid = Column(Integer, primary_key=True)
    geom = Column(Geography)

engine = create_engine('postgresql://gis:gis@localhost/testdb', echo=True)

Test.__table__.drop(engine)
Test.__table__.create(engine)
```

**Comment by adamailru** [comment]
@elemoine
I test your previous script it works but i need "show create table" not "create table", so "show create table" dose not work correctly 

I need some function like in mysql "show create table" but from SQLAlchemy model 
I don't need to create table in db from python

expect: 

     CREATE TABLE taxi.order_metadata (     
             end_point public.geography
             );

got:

    CREATE TABLE taxi.order_metadata (     
         end_point geography(GEOMETRY,-1)
         );
