### ISSUE TITLE
ORM Style Raster Model Creation

### ISSUE THREAD

**Issue by dkerkow** [geoalchemy/geoalchemy2#119]
From the docs and code, it is not clear to me if and how it is possible to have a model with a raster type created. 

So far I tried:

```python
class SourceMap(db.Model):
    id              = db.Column(db.Integer, primary_key=True)
    name            = db.Column(db.String(128), nullable=False)
    source_link     = db.Column(db.String(512), nullable=False)
    georef_raster   = db.Column(Raster)
```

...which does create the georef_raster column with type raster, but QGIS for example does not recognize it as a geometry column. Are there any tutorials out there?

**Comment by adroffner** [comment]
GEOMETRY & RASTER data are different. QGIS might not support a RASTER type. Have you described your "source_map" table within PSQL? What datatype is the "georef_raster" column?

From Google Earth's Docs:
http://www.google.com/earth/outreach/tutorials/importgis.html

GIS data is spatial data that is georeferenced to real-world locations on the Earth. There are two types of GIS data, both of which you can import: vector data and raster data.

(GEOMETRY) Vector datasets consist of points, lines, or polygons representing objects on the map. 

Raster datasets are regular grids of data, which can represent images such as satellite or aerial photography, continuous surfaces such as elevation models, or thematic classes such as land cover or habitat maps.

**Comment by dkerkow** [comment]
@adroffner I am well aware of the differences between raster and vector data, as I am coming from a GIS / geography background, but I think my issue description has been misleading. The general question behind this issue is: Does geoalchemy support the raster type and if yes, what is already possible? If it is not yet supported, are there plans to introduce it?

**Comment by loicgasser** [comment]
https://github.com/geoalchemy/geoalchemy2/blob/master/tests/test_functional.py#L188 (note you need postgis2+)

is probably the best turorial you'll find for now. So yes it is supported.

@dkerkow Confusion comes from what you said in the issue, I quote:

> but QGIS for example does not recognize it as a geometry column.

Regarding QGIS this is an other issue, latest vesions of QGIS are in theory able to read raster tables. See this link: http://postgis.net/docs/RT_FAQ.html#idp101094032

**Comment by elemoine** [comment]
I am closing this issue. Feel free to reopen if there is an issue in GeoAlchemy 2.
