### ISSUE TITLE
Travis CI Can't Run PostGIS Version 1.5 Unit Tests Anymore

### ISSUE THREAD

**Issue by adroffner** [geoalchemy/geoalchemy2#128]
The PostGIS version 1.5 tests are failing due to a missing debian package for it. Travis CI is raising the error in ".travis.yml" (I'm not skilled with Travis CI & can't fix this).

MISSING PACKAGES: The versions don't match anything in the Debian repo GitHub uses.
1) postgresql-9.1-postgis=1.5.3-2
2) postgis=1.5.3-2

See this error near line #50 of the Travis CI error log:

install:
# Install PostGIS 1.5

if [[ "$POSTGIS_VERSION" == "1.5" ]]; then sudo apt-get install -y --force-yes postgresql-9.1-postgis=1.5.3-2 postgis=1.5.3-2; fi

**Comment by micahcochran** [comment]
My suspicion is that PostGIS 1.5 is not on Travis anymore.  As I see it there are a few options, in no particular order: 
1. Drop testing for PostGIS 1.5.
2. Find another binary to install PostGIS 1.5
  - Not sure that this would be easy, (possible?).
3. download and compile the source for PostGIS 1.5.
  - Need PostgreSQL headers.
  - This will add some build time for each instance.  Maybe 5-10 minutes?
  - Configuration will be a bit harder
  - [Something like this.](http://stackoverflow.com/questions/25958789/how-to-install-postgis-1-5-in-ubuntu-14-04)



I gave it a small whirl and quickly figured out that I'm not skilled with tox configuration.

**Comment by micahcochran** [comment]
It seems that Travis-CI [has PostGIS 1.5 available once again](https://travis-ci.org/micahcochran/geoalchemy2/builds/110146688).  So Travis tests should work.

**Comment by elemoine** [comment]
Thanks @micahcochran!
