### ISSUE TITLE
build_sphinx results in maximum recursion depth exceeded in Mock()

### ISSUE THREAD

**Issue by EdwardBetts** [geoalchemy/geoalchemy2#136]
If I run "python3 ./setup.py build_sphinx" I get a traceback that ends like this:

```
  File "conf.py", line 231, in __getattr__
  File "/usr/lib/python3.5/unittest/mock.py", line 1802, in __init__
    self._mock_set_magics()  # make magic work for kwargs in init
  File "/usr/lib/python3.5/unittest/mock.py", line 1810, in _mock_set_magics
    if getattr(self, "_mock_methods", None) is not None:
  File "conf.py", line 231, in __getattr__
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Here is the problem code from doc/conf.py:

``` python
class Mock(MagicMock):
    @classmethod
    def __getattr__(cls, name):
        return Mock()
```

**Comment by elemoine** [comment]
Any idea why this works with Python 2 and not with Python 3?

**Comment by simlu** [comment]
I'd think because the max recursion depth is different? You can check and change it and see if that makes a difference.

**Comment by elemoine** [comment]
What I don't understand is that the doc build works on readthedocs. I just triggered one: https://readthedocs.org/projects/geoalchemy-2/builds/4553980/.

**Comment by EdwardBetts** [comment]
@simlu It is an infinite loop. Increasing the max recursion depth won't help you escape an infinite loop.

**Comment by simlu** [comment]
@EdwardBetts Just looked at the code now and yes, it's an infinite recursion (I only looked at the deac/text provided before). You should update the issue title / description to make that clear. So this must indeed be something where python 2 vs 3 differ in code execution.

**Comment by senarvi** [comment]
The problem is that `Mock.__get_attr__()` always constructs a new Mock, and Mock constructor calls `getattr(self, "_mock_methods")` in `_mock_set_magics()`. Sphinx started doing this recently. The simplest workaround I could think of is to replace `Mock.__get_attr__()` with:

    def __getattr__(classname, x):
        if x == "_mock_methods":
            return x._mock_methods
        else:
            return Mock()

**Comment by ifedapoolarewaju** [comment]
@senarvi your work around worked for me :)

**Comment by elemoine** [comment]
@senarvi cool! Are you able to turn this into a PR?

**Comment by senarvi** [comment]
Actually I'm not even using this software. I ended up here while looking for a solution to this issue. Maybe @ifedapoolarewaju can do a PR. :)

**Comment by ifedapoolarewaju** [comment]
I am not using the software either, but here's a [PR](https://github.com/geoalchemy/geoalchemy2/pull/148) 🙂

**Comment by EdwardBetts** [comment]
Thanks to everybody involved for investigating and fixing this bug.
