### ISSUE TITLE
Supporting spatialite

### ISSUE THREAD

**Issue by swergas** [geoalchemy/geoalchemy2#144]
Hi, do you plan to make geoalchemy2 support spatialite?
Currently, geoalchemy (1) supports it in theory, but not on recent versions of SQLAlchemy, because of https://github.com/geoalchemy/geoalchemy/pull/38 .

**Comment by elemoine** [comment]
There is no such plan at the moment. By only supporting PostGIS we can keep GeoAlchemy2 simple and support specific PostGIS features. We may want to reconsider this in the future, but I personally would not like and approve a design where we try to abstract the different backends/dialects.

I am closing the issue, but I am happy to continue the discussion.

**Comment by Juanlu001** [comment]
+1 to this. spatialite support would be nice because sqlite is nice for testing purposes. I don't think complete spatialite support is needed, but even the most basic functionality would suffice (although of course people will keep on asking for more features...)

**Comment by elemoine** [comment]
I am planning to work on adding support for Spatialite. As I said it previously I am not going to try to abstract the different backends/dialects. I will put the priority on keeping the architecture simple, adding just the minimum for supporting Spatialite.
