### ISSUE TITLE
Escape unsafe variables

### ISSUE THREAD

**Issue by matthieucan** [geoalchemy/geoalchemy2#145]
Hi,
I couldn't find in the docs how to properly escape unsafe variables, e.g. while creating a point:
```py
p = Point(geom='POINT( %s %s )' % (lng, lat))
session.add(p)
```
when I can't trust `lng` and `lat`. Is there a built-in mechanism?

If I missed anything in the docs or project issues, I'd be glad to be pointed at it. Thanks!

**Comment by tsauerwein** [comment]
`lng` and `lat` should be numbers. Converting your possible string values to numbers would make SQL injections impossible.

**Comment by matthieucan** [comment]
That makes sense.
I was thinking in the general case when the variables in the query can be text, but I just realized there won't be much of anything else than numbers.
Thank you for your fast answer.
