### ISSUE TITLE
Sql server support ?

### ISSUE THREAD

**Issue by moagarw** [geoalchemy/geoalchemy2#150]
Any plan to support sql server in future ? If yes, by when ? Our project needs it.

Thanks

**Comment by elemoine** [comment]
No there's no such plan. Our goal has been to keep geoalchemy2 simple and PostGIS-centric. A separate repo, possibly based on geoalchemy2, would be good. We could possibly have it under the `geoalchemy` GitHub organization.

**Comment by moagarw** [comment]
ok thanks
