### ISSUE TITLE
Replace shapely with geomet

### ISSUE THREAD

**Issue by dave-nm** [geoalchemy/geoalchemy2#155]
`shapely` is a big dependency since it requires the `GEOS` library. Only WKT/WKB functions are used from it, so I would recommend switching to use [geomet](https://github.com/geomet/geomet) since it's a pure Python solution.

**Comment by elemoine** [comment]
Note that Shapely is not a dependency of GeoAlchemy2. GeoAlchemy2 just provides some integration with Shapely, but Shapely is certainly not required for using GeoAlchemy. So there's no such thing as "Replacing Shapely with…" in GeoAlchemy2 :)

That being said, we could add a `geoalchemy2.geomet` (or `geoalchemy2.geomet_`) module, in the same way we have a `geoalchemy.shapely` module. Up for a PR?

**Comment by dave-nm** [comment]
I found an [issue with geomet](https://github.com/geomet/geomet/issues/30), so I'll probably just stick with shapely.

**Comment by larsbutler** [comment]
As mentioned on https://github.com/geomet/geomet/issues/30, I think this is an issue with the input--at least based on my current understanding. Let me know what you think.
