### ISSUE TITLE
fix support of mixed geometry

### ISSUE THREAD

**Issue by tomkralidis** [geoalchemy/geoalchemy2#158]
As per https://groups.google.com/forum/#!topic/geoalchemy/LxC9y2JsXhg, in PostgreSQL it is [possible](https://gist.github.com/tomkralidis/3f11c88969e0c2d9d7a213827d75ab56#file-test_zgeom-sql) to have a geometry type and be able to insert (in my case) `POINT` and `POINTZ` geometries accordingly.

[Attempting this](https://gist.github.com/tomkralidis/3f11c88969e0c2d9d7a213827d75ab56#file-test_zgeom-py) in `GeoAlchemy2==0.4.0` yields issues of dimension constraints.

**Comment by tomkralidis** [comment]
Relevant discussion on postgis-users: https://lists.osgeo.org/pipermail/postgis-users/2017-July/042279.html

**Comment by elemoine** [comment]
Cool. So my suggestion is to support `geometry_type=None`. And in that case the geometry column will be created using `geom geometry` (no typmod applied). Works for you Tom?

**Comment by tomkralidis** [comment]
+1. Let me know when I can test. Thanks.

**Comment by elemoine** [comment]
@tomkralidis see #161.
