### ISSUE TITLE
New pypi release

### ISSUE THREAD

**Issue by JacobHayes** [geoalchemy/geoalchemy2#167]
There hasn't been a new release published to Github nor pypi in quite a while. I've had to create some custom wheels for code dependent on new changes. Could a new release be created and published? I'd be willing if there's anything I can do to help.

**Comment by elemoine** [comment]
I just released 0.4.1. See https://pypi.python.org/pypi/GeoAlchemy2/0.4.1. Thanks for suggesting making a new release.
