### ISSUE TITLE
&& (overlap) operator support

### ISSUE THREAD

**Issue by ishiland** [geoalchemy/geoalchemy2#172]
Hello,
I am trying to convert this query to geoalchemy2:
```
SELECT *
FROM my_table
WHERE my_table.the_geom && ST_MakeEnvelope(-75.97464419082118,39.523869271308314,-72.18532985820512,41.552541030492364);
```

Here is my (incorrect) attempt with geoalchemy:
```
class ST_MakeEnvelope(GenericFunction):
    name = 'ST_MakeEnvelope'
    type = Geometry

box = "-75.97464419082118,39.523869271308314,-72.18532985820512,41.552541030492364"

results = my_table.query.filter(my_table.the_geom, ST_MakeEnvelope(box)).first()
```

> sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) argument of AND must be type boolean, not type geometry

I have not seen any documentation on how you can use the && operator.  Is this possible? I really just need to execute the `ST_MakeEnvelope` function. 

Thanks

**Comment by tsauerwein** [comment]
I posted an answer in your [GIS SE question](https://gis.stackexchange.com/questions/268724/geoalchemy2-support-for-st-makeenvelope/268881#268881). Please close this issue if your problem was resolved.
