### ISSUE TITLE
Can't add function GeometryType due to AssertionError

### ISSUE THREAD

**Issue by dkerkow** [geoalchemy/geoalchemy2#174]
I needed to add the PostGIS function `GeometryType` by subclassing from `GenericFunction` as described [here](https://geoalchemy-2.readthedocs.io/en/latest/spatial_functions.html#geoalchemy2.functions.GenericFunction), but get an error because the BaseComparator class asserts all function names to start with 'ST_':

```python
# Function names that don't start with "ST_" are rejected.
# This is not to mess up with SQLAlchemy's use of
# hasattr/getattr on Column objects.

if not name.startswith('ST_'):
    raise AttributeError
```

I worked around this by using the slightly different PostGIS function `ST_GeometryType`.

Would there be another way to solve that?

**Comment by elemoine** [comment]
Please reopen if needed.
