### ISSUE TITLE
Tables created by geoalchemy appear twice in QGIS

### ISSUE THREAD

**Issue by mangecoeur** [geoalchemy/geoalchemy2#178]
Not sure if this is a geoalchemy problem or a QGIS issue, but it's wierd: When i create a postgis table with sqlalchemy/geoalchemy from python, the table appears twice in the QGIS database browser - but only one of them correctly loads as a layer. This is on Windows, latest geoalchemy, python 3.6. When i browse the DB with PyCharm i see a single table. I have no such issues with tables created with raw SQL which is why i think it might be a geoalchemy issue - perhaps the geometry column is somehow being registered twice with postgis??

**Comment by elemoine** [comment]
Please check in PostGIS first. I really doubt the issue is related to GeoAlchemy.
