### ISSUE TITLE
Intersects(polygon) returns non-intersecting linear geoms

### ISSUE THREAD

**Issue by timmayo-ubi** [geoalchemy/geoalchemy2#183]
We have recently upgraded from GeoAlchemy to GeoAlchemy2 0.4.2. One of our own tests is showing a change in behaviour: a spatial query is returning unexpected extra results.

 The test looks for linear objects intersecting a target polygon. In geoalchemy2 it is returning linear objects that do not intersect the polygon .. but whose bounding boxes do (see pic).

![pic1](https://user-images.githubusercontent.com/3224256/42369975-7857eb94-8103-11e8-8be6-39e0ed15ab6d.png)

The query we are doing is:

     query = db.session.query(model).filter( model.the_geom.intersects(shapely_geom.wkt) )

I guess there might be a neater way of doing this in GeoAlchemy2 ... but since this worked in GeoAlchemy it would be good if it gave correct results (would make upgrading easier).

I have attached our test code and data. Also the SQL generated by GeoAlchemy and GeoAlchemy2. Let me know if your require anything else

Cheers .. and thanks for all your hard work!

[geoalchemy2_intersects_issue.py.txt](https://github.com/geoalchemy/geoalchemy2/files/2169767/geoalchemy2_intersects_issue.py.txt)

[sheath_with_loc.1.json.txt](https://github.com/geoalchemy/geoalchemy2/files/2169825/sheath_with_loc.1.json.txt)

[geoalchemy_sql.txt](https://github.com/geoalchemy/geoalchemy2/files/2169828/geoalchemy_sql.txt)

[geoalchemy2_sql.txt](https://github.com/geoalchemy/geoalchemy2/files/2169829/geoalchemy2_sql.txt)

**Comment by elemoine** [comment]
Use this:

```py
query = db.session.query(model).filter(model.the_geom.ST_Intersects(shapely_geom.wkt))
```

The `intersects` function actually corresponds to the `&&` operator.

See http://geoalchemy-2.readthedocs.io/en/latest/spatial_operators.html. The "Spatial Operators" section of the ORM tutorial mentions it as well: http://geoalchemy-2.readthedocs.io/en/latest/orm_tutorial.html#spatial-relationship.

I am closing the issue, but feel free to re-open if needed.
