### ISSUE TITLE
'Geometry' object has no attribute 'ST_AsGeoJSON'

### ISSUE THREAD

**Issue by Links7094** [geoalchemy/geoalchemy2#197]
when i using `self.db.session.query(model.geom.ST_AsGeoJSON())`  throws an AttributeError：'Geometry' object has no attribute 'ST_AsGeoJSON'

**Comment by elemoine** [comment]
@Links7094 can you please provide a test-case that I can just execute to reproduce the issue you're seeing?

**Comment by Links7094** [comment]
> @Links7094 can you please provide a test-case that I can just execute to reproduce the issue you're seeing?

Thank you ! it's ok now....
