### ISSUE TITLE
GE part of logo looks similar to General Electric logo...

### ISSUE THREAD

**Issue by johnkea** [geoalchemy/geoalchemy2#200]
Hey gusy, thanks for great work, I really appreciate we all have now ORM for GIS! Here is small comment on your logo though, in the docs pages you have GE colored black, the font make it looks like General Electric logo. Please, have a look:
[GeoAlchemy-2 docs](https://geoalchemy-2.readthedocs.io/en/latest/index.html)
[General Electric wiki](https://en.wikipedia.org/wiki/General_Electric)
Have a  good time!

**Comment by adrien-berchet** [comment]
Hi @johnkea 
Sorry for the (very) late answer.
The fonts in the logos are indeed quite similar but I don't think they can be mixed up so it should not be a problem.
