### ISSUE TITLE
spatialite no such function: ST_AsGeoJSON

### ISSUE THREAD

**Issue by TomGoBravo** [geoalchemy/geoalchemy2#202]
I'm using the flask-admin geoa extension to edit Geometry columns in a spatialite database.

```
".../flask-admin/flask_admin/contrib/geoa/typefmt.py", line 22, in geom_formatter
geojson = view.session.query(view.model).with_entities(func.ST_AsGeoJSON(value)).scalar()
causes
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such function: ST_AsGeoJSON [SQL: 'SELECT ST_AsGeoJSON(GeomFromEWKB(?)) AS "ST_AsGeoJSON_1"']
```
It seems that geoalchemy expects a function named ST_AsGeoJSON but spatialite has only AsGeoJSON. I didn't see a trivial way to add an alias in geoalchemy2/functions.py so I fetched the spatialite 4.3 source and added:

```
diff -r spatialite-4.3.0a/src/spatialite/spatialite.c spatialite-4.3.0a-modified/src/spatialite/spatialite.c
35951a35952,35960
>     sqlite3_create_function_v2 (db, "ST_AsGeoJSON", 1,
>                               SQLITE_UTF8 | SQLITE_DETERMINISTIC, cache,
>                               fnct_AsGeoJSON, 0, 0, 0);
>     sqlite3_create_function_v2 (db, "ST_AsGeoJSON", 2,
>                               SQLITE_UTF8 | SQLITE_DETERMINISTIC, cache,
>                               fnct_AsGeoJSON, 0, 0, 0);
>     sqlite3_create_function_v2 (db, "ST_AsGeoJSON", 3,
>                               SQLITE_UTF8 | SQLITE_DETERMINISTIC, cache,
>                               fnct_AsGeoJSON, 0, 0, 0);
```
This fixed my problem for now. I making this issue to help other people and see if there is a long term solution within geoalchemy.

**Comment by elemoine** [comment]
Have you tried the following?


```py
from geoalchemy2.functions import GenericFunction

class AsGeoJSON(GenericFunction):
    name = 'AsGeoJSON'
    identifier = 'ST_AsGeoJSON'
```

It may not work in every case but it may be worth trying in your case.

**Comment by elemoine** [comment]
If it works for you could add that to the SpatiaLite tutorial.

**Comment by TomGoBravo** [comment]
Nice, that does work.

Aside from this problem it looks like the flask-admin extension works with SpatiaLite and PostGIS with only changes in the configuration; the core part of the code is independant and oblivious to the database implementation. Do you think there is a good solution that avoids special handling per database in the code calling geoalchemy2?

Thank you for puzzling on this little detail.

**Comment by elemoine** [comment]
@TomGoBravo could you please be a big more specific? I'm having trouble understanding what you precisely mean. Thanks.

**Comment by TomGoBravo** [comment]
SpatiaLite and PostGIS use different identifiers in SQL to produce the same output. geoalchemy2 provides a layer of abstraction that makes it easy to send a particular identifier. The code that calls geoalchemy2 needs to use `class AsGeoJSON` (in your first comment) when the underlying database is SpatiaLite or the normal func.ST_AsGeoJSON when the underlying database is PostGIS. What I'd like is one function invokes AsGeoJSON for SpatiaLite or ST_AsGeoJSON for PostGIS. If such a function existed then the core part of the flask-admin extension can continue to remain independent of the underlying database.

**Comment by elemoine** [comment]
I see you're coming from.

What do you think about https://github.com/geoalchemy/geoalchemy2/compare/ele_st? Can you give it a try?

**Comment by TomGoBravo** [comment]
Nice! A small correction, it is AsGeoJSON not GeoJSON. See https://github.com/geoalchemy/geoalchemy2/pull/203

Another thing I noticed is func seems to look up function names ignoring case, but the compiles correction only applies for use exact case. So func.ST_AsGeoJSON works but not func.ST_AsGeoJson. This is easy to fix on the caller side.

Thank you.

**Comment by elemoine** [comment]
@TomGoBravo thanks. I've modified my [ele_st](https://github.com/geoalchemy/geoalchemy2/compare/ele_st) to go one step further and remove the `use_st_prefix` argument, and rely on sqlite-compiled functions instead. It looks like a step in the right direction, without adding too much complexity to GeoAlchemy. What do you think?

**Comment by TomGoBravo** [comment]
Oh nice. I hadn't looked for tests :-( and it looks like geoalchemy2 has good ones. How about a test that exercises the ST_AsGeoJSON vs AsGeoJSON fix?

What about functions that have only names with an ST_ prefix in spatialite ? For example looking at https://www.gaia-gis.it/fossil/libspatialite/annotate?filename=src/spatialite/spatialite.c&checkin=9149f6edcd58b10da22f0603447e9d5760a71ccc the function fnct_WkbToSql only appears as ST_WKBToSQL ?

```
srcstr = open('code/spatialite-4.3.0a-modified/src/spatialite/spatialite.c').read()

fnct_names = {}

for m in re.finditer(r'sqlite3_create_function_v2[^\(]*\(db, *\"(\w+)\"[^)]+(fnct_\w+),[^\)]+\);', srcstr):
  fnct_names.setdefault(m.group(2), []).append(m.group(1))

for fnct, names in fnct_names.items():
  names.sort(key=lambda n: (not n.startswith("ST_"), n))
  info = ''
  if all(n.startswith('ST_') for n in names):
      info = 'ST_ only names!!!'
      print(fnct + '   ' + info)
      print('   ' + ' '.join(names))
```
finds about 20 of these, though generally uncommonly used functions, like ST_Is3D.

**Comment by elemoine** [comment]
> How about a test that exercises the ST_AsGeoJSON vs AsGeoJSON fix?

Yep, I'll add tests covering this.

> What about functions that have only names with an ST_ prefix in spatialite ?

I don't see the problem for those. They're already supported. What problem are you looking at exactly?
