### ISSUE TITLE
Question regarding usage of WKT and WKB

### ISSUE THREAD

**Issue by nikoladsp** [geoalchemy/geoalchemy2#205]
Hi all,
I recently start using GA2 and have few questions:

1. shall I use WKB or WKT when exchanging data with UI (JS, web). What is the recommendation?
2. is it possible to use WKB when e.g. inserting data to the DB; like: `item.location = b'0103000020110F000001000000050000009FDE97E1FECC4341FC419E6B3458514101A7BAA6A56A4441FC419E6B3458514101A7BAA6A56A444118348F73B69551419FDE97E1FECC434118348F73B69551419FDE97E1FECC4341FC419E6B34585141'`?
3. I have noticed that I must put SRID each time when adding items to the DB; like: `SRID=3857;POLYGON((0 0,1 0,1 1,0 1,0 0))` although I put the default to 3857 when defined model class

Thank you in advance

Kindest regards

**Comment by elemoine** [comment]
>     1. shall I use WKB or WKT when exchanging data with UI (JS, web). What is the recommendation?

I'd recommend GeoJSON.



>     2\. is it possible to use WKB when e.g. inserting data to the DB

Yes. Use `WKBElement`:

```py
import binascii
b = binascii.unhexlify('0103000020110F000001000000050000009FDE97E1FECC4341FC419E6B3458514101A7BAA6A56A4441FC419E6B3458514101A7BAA6A56A444118348F73B69551419FDE97E1FECC434118348F73B69551419FDE97E1FECC4341FC419E6B34585141')
item.location = WKBElement(b)
```

>     3\. I have noticed that I must put SRID each time when adding items to the DB; like: `SRID=3857;POLYGON((0 0,1 0,1 1,0 1,0 0))` although I put the default to 3857 when defined model class

Yes, that's the way PostGIS works. The SRID is set both in the geometry columns, and in the geometries  you insert in that column.

**Comment by nikoladsp** [comment]
Thank you kindly!
