### ISSUE TITLE
Nesting functions

### ISSUE THREAD

**Issue by stev-0** [geoalchemy/geoalchemy2#206]
It's not clear to me from the docs if postgis functions can be nested and if so, how?

**Comment by stev-0** [comment]
This does seem to be possible using a session query e.g.

`db.session.query(Model.r_id,Model.r_width,Model.r_length,Model.wb_id,func.ST_AsGeoJson(func.ST_Transform(Model.geom,4326))).filter(Model.wb_id == str(wbid)).all()`

**Comment by elemoine** [comment]
What's the problem?
