### ISSUE TITLE
Need to use pyproj library to convert WGS84 to Webmercator coordinate system

### ISSUE THREAD

**Issue by thoyo** [geoalchemy/geoalchemy2#207]
I am trying to convert a GeoJSON to WKB and WKT in different coordinate systems (WGS84 and Webmercator). 

Versions I am using:
```
GeoAlchemy2==0.5.0
Shapely==1.6.4.post2
pyproj==1.9.5.1
```

While for WGS84 it works, for Webmercator I need to go through some additional steps using the pyrproj library. 

See the following script as an example:
```
import geoalchemy2.shape
import shapely.geometry
from pyproj import Proj, transform

WGS84_COORDINATE_SYSTEM = 4326
WEBMERCATOR_COORDINATE_SYSTEM = 3857

geojson = {"coordinates": [2.141290, 41.380849], "type": "Point"}
coordinates = geojson["coordinates"]
shape = shapely.geometry.shape(geojson)


def gen_wkb(srid, method):
    if method == "geoalchemy":
        wkb_element = geoalchemy2.shape.from_shape(shape, srid=srid)
    elif method == "pyproj" and srid == WEBMERCATOR_COORDINATE_SYSTEM:
        in_proj = Proj(init=f"epsg:{WGS84_COORDINATE_SYSTEM}")
        out_proj = Proj(init=f"epsg:{WEBMERCATOR_COORDINATE_SYSTEM}")
        x, y = transform(in_proj, out_proj, coordinates[0], coordinates[1])
        point = shapely.geometry.Point(x, y)
        wkb_element = geoalchemy2.shape.from_shape(point, srid=WEBMERCATOR_COORDINATE_SYSTEM)

    wkt_element = geoalchemy2.shape.to_shape(wkb_element).to_wkt()
    print(wkb_element.desc)
    print(wkt_element)
    print("\n")

print("WGS84 computed with geoalchemy: ")
gen_wkb(WGS84_COORDINATE_SYSTEM, "geoalchemy")

print("Webmercator computed with geoalchemy: ")
gen_wkb(WEBMERCATOR_COORDINATE_SYSTEM, "geoalchemy")

print("Webmercator computed with pyproj: ")
gen_wkb(WEBMERCATOR_COORDINATE_SYSTEM, "pyproj")
```

That produces this output:
```
WGS84 computed with geoalchemy: 
0101000000c503caa65c2101406edbf7a8bfb04440
POINT (2.1412900000000001 41.3808489999999978)


Webmercator computed with geoalchemy: 
0101000000c503caa65c2101406edbf7a8bfb04440
POINT (2.1412900000000001 41.3808489999999978)


Webmercator computed with pyproj: 
0101000000d6ece07ffa180d41ec1e4509e2555341
POINT (238367.3124407294089906 5068680.1448437981307507)
```

Which looks like `geoalchemy2.shape.from_shape(shape, srid=srid)` is ignoring the `srid` argument, since it produces the exact same result for `srid=4326` and `srid=3857`.

Any idea what is going on here? 

Thanks

**Comment by elemoine** [comment]
geoalchemy2.shape.from_shape doesn't do data reprojection. The srid argument just specifies the spatial reference system of the provided coordinates.

For reprojecting the data you can use either pyproj or PostGIS. In the example provided in the issue description there is no interaction with the database, so it sounds like pyproj is what you want to use.

Feel free to tell us more about your use-case if you want more help and explanations.

**Comment by thoyo** [comment]
Thanks for your reply! From the documentation I had understood that from_shape was able to do the reprojection. Using pyproj is fine with me, I just thought I was taking a long detour instead of following a straight line between point A and B.
