### ISSUE TITLE
Error creating table with Geography type column for spatialite

### ISSUE THREAD

**Issue by eydelrivero** [geoalchemy/geoalchemy2#214]
I've followed the tutorial for SpatiaLite [here](https://geoalchemy-2.readthedocs.io/en/latest/spatialite_tutorial.html) and it works ok with the `Geometry` column. This is the code up to the creation of the `Lake` table:

```python
from geoalchemy2 import Geometry, Geography
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.sql import select, func
from sqlalchemy.event import listen
from sqlalchemy.ext.declarative import declarative_base


def load_spatialite(dbapi_conn, connection_record):
    dbapi_conn.enable_load_extension(True)
    dbapi_conn.load_extension('mod_spatialite')


# connecting to a SpatiaLite database requires an Engine. This is how you create one for SpatiaLite:
engine = create_engine('sqlite:///gis.db', echo=True)
listen(engine, 'connect', load_spatialite)

# At this point you can test that you are able to connect to the database:
conn = engine.connect()

# One additional step is required for using SpatiaLite: create the geometry_columns and spatial_ref_sys metadata tables.
#  This is done by calling SpatiaLite’s InitSpatialMetaData function:
conn.execute(select([func.InitSpatialMetaData()]))

# Before going further we can close the current connection:
conn.close()

# create a mapping between a Python class and a database table.
Base = declarative_base()


class Lake(Base):
    __tablename__ = 'lake'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    geom = Column(Geometry(geometry_type='POLYGON', management=True))

# create the lake table in the gis.db database:
Lake.__table__.create(engine)
```
In this case the table is crated with no issues. But then I tried to use the `Geography` type instead of the `Geometry` type by replacing 

`geom = Column(Geometry(geometry_type='POLYGON', management=True))` 

with 

`geom = Column(Geography(geometry_type='POLYGON', srid=4326))`

as stated in the documentation for the `Geography` type [here](https://geoalchemy-2.readthedocs.io/en/latest/types.html#geoalchemy2.types.Geography). In this second case, the creation of the table fails with

`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "POLYGON": syntax error [SQL: '\nCREATE TABLE lake (\n\tid INTEGER NOT NULL, \n\tname VARCHAR, \n\tgeom geography(POLYGON,4326), \n\tPRIMARY KEY (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)`

I wonder if the `Geography` type is supported for SpatiaLite or am I missing something else?

## My setup:
macOs High Sierra 10.13.6
python 3.7.2
libspatialite: stable 4.3.0a
SQLAlchemy 1.2.10
GeoAlchemy2 0.6.1

**Comment by elemoine** [comment]
To my knowledge SpatiaLite does not have a Geography type.
