### ISSUE TITLE
Granting write access to Adrien Berchet

### ISSUE THREAD

**Issue by elemoine** [geoalchemy/geoalchemy2#218]
@adrien-berchet has proposed good and solid patches to GeoAlchemy, and he's even contributing to SQLAlchemy for GeoAlchemy-related things. So I proposed him to become an official GeoAlchemy developer/maintainer (with write access to the repo) and he accepted. So I will add him to the developer team. Thank you Adrien.

**Comment by adrien-berchet** [comment]
Thanks! :blush:
