### ISSUE TITLE
How to do a spacial join?

### ISSUE THREAD

**Issue by troyswanson** [geoalchemy/geoalchemy2#220]
Consider two objects: points and polygons.

I would like to create a relationship on the point object so that I can see which polygons (if any), the point is contained within.

Writing a query for this in raw SQL is pretty straightforward:

```sql
SELECT *
FROM points
FULL JOIN polygons ON ST_Within(points.the_point, polygons.the_area)
```

How would I represent this relationship in geoalchemy?

**Comment by elemoine** [comment]
Are you using SQLAlchemy Core or ORM? Do you want to configure the join condition in the model or at query time? Also, have you looked at the SQLAlchemy docs? Joining between tables is thoroughly explained in the SQLAlchemy docs...

**Comment by troyswanson** [comment]
Hello @elemoine! Thanks for responding.

I'm using SQLAlchemy ORM, and I'd like to configure the relationship in the model. I've taken a look at the SQLAlchemy docs regarding joins, and from what I can tell, they mostly rely on some kind of foreign key relationship, which this wouldn't really apply to.

The only thing that seems to be relevant is using [custom operators in the join condition](https://docs.sqlalchemy.org/en/13/orm/join_conditions.html#using-custom-operators-in-join-conditions), but I'm having difficulty writing this relationship in code.

**Comment by elemoine** [comment]
It's actually more involved than I expected… And I am suprised I haven't met this before.

I tried this but it does not work:

```py
from sqlalchemy import create_engine, MetaData, Column, Integer
from sqlalchemy.orm import sessionmaker, relationship
from sqlalchemy.ext.declarative import declarative_base
from geoalchemy2 import Geometry
from geoalchemy2 import functions  # NOQA


engine = create_engine("postgresql://elemoine@localhost/gis", echo=True)
metadata = MetaData(engine)

Base = declarative_base(metadata=metadata)


class Polygon(Base):
    __tablename__ = "polygon"
    id = Column(Integer, primary_key=True)
    geom = Column(Geometry("POLYGON", srid=4326))
    points = relationship(
        "Point",
        primaryjoin="func.ST_Contains(foreign(Polygon.geom), remote(Point.geom))",
        viewonly=True,
    )


class Point(Base):
    __tablename__ = "point"
    id = Column(Integer, primary_key=True)
    geom = Column(Geometry("POINT", srid=4326))


metadata.drop_all(checkfirst=True)
metadata.create_all()


polygon = Polygon()
```

I get this error when instantiating `Polygon`:

```
sqlalchemy.exc.ArgumentError: Relationship Polygon.points could not determine any unambiguous local/remote column pairs based on join condition and remote_side arguments.  Consider using the
remote() annotation to accurately mark those elements of the join condition that are on the remote side of the relationship.
```

The relevant SQLA doc is indeed [custom operators in join condition](https://docs.sqlalchemy.org/en/13/orm/join_conditions.html#using-custom-operators-in-join-conditions). It indeed works with operators and the `is_comparison` flag, but it does not work with PostGIS functions.

Maybe @zzzeek could help us a bit here.

**Comment by zzzeek** [comment]
See https://docs.sqlalchemy.org/en/13/core/functions.html#sqlalchemy.sql.functions.FunctionElement.as_comparison as well as the changeset that mentions this issue, if we could confirm the example I documented works that would be great.

**Comment by elemoine** [comment]
Thanks @zzzeek! It works. I need to document this in the GeoAlchemy docs, as spatial joins like this are very common.

My example, modified:

```py
from sqlalchemy import create_engine, MetaData, Column, Integer
from sqlalchemy.orm import sessionmaker, relationship
from sqlalchemy.ext.declarative import declarative_base
from geoalchemy2 import Geometry
from geoalchemy2 import functions  # NOQA


engine = create_engine("postgresql://elemoine@localhost/gis", echo=True)
metadata = MetaData(engine)

Base = declarative_base(metadata=metadata)


class Polygon(Base):
    __tablename__ = "polygon"
    id = Column(Integer, primary_key=True)
    geom = Column(Geometry("POLYGON", srid=4326))
    points = relationship(
        "Point",
        primaryjoin="func.ST_Contains(foreign(Polygon.geom), remote(Point.geom)).as_comparison(1, 2)",
        viewonly=True,
        uselist=True,
        lazy="joined",
    )


class Point(Base):
    __tablename__ = "point"
    id = Column(Integer, primary_key=True)
    geom = Column(Geometry("POINT", srid=4326))


metadata.drop_all(checkfirst=True)
metadata.create_all()


polygon = Polygon()
polygon.geom = "srid=4326;POLYGON((0 0,0 2,2 2,2 0,0 0))"

point1 = Point()
point1.geom = "srid=4326;POINT(3 3)"

point2 = Point()
point2.geom = "srid=4326;POINT(1 1)"


Session = sessionmaker(bind=engine)
session = Session()

session.add_all([polygon, point1, point2])
session.commit()

session = Session()
for poly in session.query(Polygon).join(Polygon.points):
    print(poly.points[0].id)
```

**Comment by troyswanson** [comment]
I was surprised when I couldn't find any previous issues or docs about this as well, but I'm very grateful for your time. This is awesome work.

@elemoine I can leave this issue open as something to be auto-closed once new documentation has been written and merged, or you can close it and process that work separately.

Thank you again!

**Comment by elemoine** [comment]
@troyswanson yep, let's leave this open for now.

There still is an unrelated issue when using lazy loading (that is without `lazy="joined"` in my example). I get this error when attempting to access the `points` property of a `Polygon` object:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'WKBElement'
[SQL: SELECT point.id AS point_id, ST_AsEWKB(point.geom) AS point_geom
FROM point
WHERE ST_Contains(ST_GeomFromEWKT(%(param_1)s), point.geom)]
[parameters: {'param_1': <WKBElement at 0x7f0739e07780; 0103000020e610000001000000050000000000000000000000000000000000000000000000000000000000000000000040000000000000004000000000000000400000000000000040000000000000000000000000000000000000000000000000>}]
(Background on this error at: http://sqlalche.me/e/f405)
```

I'd like to figure this one out as well.

**Comment by troyswanson** [comment]
For the rest of the world, if you get an error like this...

```
AttributeError: Neither 'ST_Contains' object nor 'Comparator' object has an attribute 'as_comparison'
```

...it's because you need to be on version 1.3 or greater. 1.2 does not support this.

**Comment by elemoine** [comment]
> There still is an unrelated issue when using lazy loading (that is without `lazy="joined"` in my example). I get this error when attempting to access the `points` property of a `Polygon` object:

https://github.com/geoalchemy/geoalchemy2/pull/221 proposes a fix for that particular issue.
