### ISSUE TITLE
Spatial Index assuming public schema

### ISSUE THREAD

**Issue by zrayn** [geoalchemy/geoalchemy2#230]
When creating a spatial index for a declaratively defined table that does not specify the schema, `public` is assumed to be the schema for the table (https://github.com/geoalchemy/geoalchemy2/blob/master/geoalchemy2/__init__.py#L81). My issue here is I have the default schema for my DB set up to be `my_schema`, so my table is created in that schema, then when alembic tries to generate the spatial index for the column geoalchemy is prepending a `public.` to the index table, thereby causing the index creation to fail.

**Comment by elemoine** [comment]
@zrayn thanks for reporting this. It indeed sounds like a GeoAlchemy bug. GeoAlchemy should not assume "public" when no schema is specified.

**Comment by elemoine** [comment]
@zrayn are you able to give https://github.com/geoalchemy/geoalchemy2/pull/231 a try?

**Comment by zrayn** [comment]
Yep, that solves the problem
