### ISSUE TITLE
How to convert WKTElement (with srid) to Geometry?

### ISSUE THREAD

**Issue by Sieboldianus** [geoalchemy/geoalchemy2#235]
I find working with Geoalchemy2 really nice, but one thing bothers me: I can't seem to find out how to create a Geometry from a WKTE-String that is returned from PostGIS/Postgres. I need a Geometry because I need to access/extract lat/lng coordinates from a point that is returned from PostGis.

What I do is more than crazy (but somehow works):

```python
# this is how the string looks that I get back from Postgres:
geom = 'SRID=4326;POINT(20.0 40.0)'
def get_coordinates_from_geom(
        geom: str) -> Coordinates:
    """Convert EWKT representation (with srid) to geometry"""
    geom = geom.replace("SRID=4326;", "")
    shply_geom = wkt.loads(geom)
    # shply_geom = to_shape(geom) (doesn't work)
    coordinates = Coordinates(lng=shply_geom.x, lat=shply_geom.y)
    return coordinates
```

I can do this:
```python
wkte_geom = WKTElement(geom, extended=True)
```

But then, how do I go from WKTElement to WKT to `wkt.loads()` or `to_shape()`?

**Comment by adrien-berchet** [comment]
Indeed, it seems that `geoalchemy2.shape.to_shape()` does not support EWKT. Can you try with https://github.com/geoalchemy/geoalchemy2/pull/236 please?

**Comment by Sieboldianus** [comment]
Thanks, I will try it! Likely need a few days to report back...

**Comment by SergeBouchut** [comment]
Hello @Sieboldianus, if your intention is to extract lat/lng coordinates, maybe the best approach in your case is to perform this operation directly in database.

```python
query(func.ST_X(table.col).label(lng), func.ST_Y(table.col).label(lat))
```

For better performance, I recommend you to load your geometry in shapely objects only when you have no other choice. See postgis functions in reference documentation: https://postgis.net/docs/reference.html

**Comment by Sieboldianus** [comment]
Many thanks @SergeBouchut , that sounds the correct approach. I hadn't had time to look at this since we've been working on a complete redesign of the SQLAlchemy Model and underlying database. My post-processing approach described initially also stems from not really knowing how to modify SQLAlchemy types returned on requests to the db - I defenitly need to look into this, your code sample is a great pointer in the right direction!

I'll close this issue but will report back.
