### ISSUE TITLE
Data is missing from bulk inserts

### ISSUE THREAD

**Issue by lkiesow** [geoalchemy/geoalchemy2#245]
When inserting a lot of data, SQLAlchemy's `session.bulk_save_objects` speeds up the operation immensely. Unfortunately, it seems like  geoalchemy2 data types are lost in the process.

Executing something like this should yield four valid database entries:

```python
objects = []
for i in range(2):
    objects.append(Region(lon=i, lat=i))
session.bulk_save_objects(objects)
session.commit()
for i in range(2):
    session.add(Region(lon=i+10, lat=i+10))
session.commit()
```

<details>
<summary>Expand full example</summary>

```python
from sqlalchemy import create_engine, Column, Integer, Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

import geoalchemy2

database = 'postgresql://user:pass@127.0.0.1/db'

# Global session variable. Set on initialization.
__session__ = None

# Base Class of all ORM objects.
Base = declarative_base()


class Region(Base):
    __tablename__ = 'region'
    id = Column(Integer, primary_key=True)
    longitude = Column(Float)
    latitude = Column(Float)
    geom = Column(geoalchemy2.Geometry(geometry_type="POINT"))

    def __init__(self, lon, lat):
        self.longitude = lon
        self.latitude = lat
        self.geom = geoalchemy2.elements.WKTElement(f"POINT({lon} {lat})")


if __name__ == '__main__':
    Engine = create_engine(database)
    session = sessionmaker(bind=Engine)()
    Base.metadata.create_all(Engine)
    objects = []
    for i in range(2):
        region = Region(lon=i, lat=i)
        objects.append(region)
    session.bulk_save_objects(objects)
    session.commit()
    for i in range(2):
        session.add(Region(lon=i+10, lat=i+10))
    session.commit()

```
</details>

But the result is that `geom` is missing from the database entries added via `bulk_save_objects`:

```sh
% psql -h 127.0.0.1 --password user db
psql (11.5)
emissionsapi=> select * from region;
 id | longitude | latitude |                    geom                    
----+-----------+----------+--------------------------------------------
  5 |         0 |        0 | 
  6 |         1 |        1 | 
  7 |        10 |       10 | 010100000000000000000024400000000000002440
  8 |        11 |       11 | 010100000000000000000026400000000000002640
(4 rows)
```

I've used GeoAlchemy2 version 0.6.3 for this. Any idea of what the problem could be?

**Comment by adrien-berchet** [comment]
I think this behaviour is normal. As stated in [SQLAlchemy doc](https://docs.sqlalchemy.org/en/13/orm/persistence_techniques.html#bulk-operations), the `bulk_save_objects()` method bypasses most of the usual Python processes and just sends the raw data to the DB. The `geometry` objects need some processes in order to be inserted in the DB (e.g. add `ST_GeomFromText` to the query) but they are bypassed in this case. So I don't think it is possible to use bulk operations with complex objects (see [here](https://stackoverflow.com/questions/37338047/bulk-saving-complex-objects-sqlalchemy), another one had similar issue with relationships).

**Comment by adrien-berchet** [comment]
I gave an example to speedup inserts or updates here:
https://github.com/emissions-api/emissions-api/pull/84
