### ISSUE TITLE
WKBElement not comparing as expected

### ISSUE THREAD

**Issue by matthew-emw** [geoalchemy/geoalchemy2#246]
I began by raising this issue over at SQLAlchemy: https://github.com/sqlalchemy/sqlalchemy/issues/5093

(Quoting from that report)
observed behaviour:
i'm using sqlalchemy 1.3.11 with a PostgreSQL/PostGIS backend
i have a table with a Geography column that represents a GIS point
i retrieve row from that table
i update the GIS point _with the same lat/lon values as before_
i observe an unexpected SQL update is issued to the database
(End quote)

Discussion with Mike Bayer @zzzeek suggested that the issue might lie within geoalchemy2, with its root in the comparison of the WKBElement objects.

As it stands, SQLAlchemy is considering my retrieved-from-database geography point to be different from my newly created one, even though they have the same latitude, longitude, srid and WKB

```
attribute geo_point has changes: True
added: 01010000006095875cdb5d184039ecbe63781e4a40
deleted: 01010000006095875cdb5d184039ecbe63781e4a40
```

My belief is that if two WKBElement objects have the same hexlify'd WKB contained within them, then they can be considered to be equal.

Adding methods as follows to WKBElement gives me the behaviour I expect:
```
    def __eq__(self, other):
        return self.desc == other.desc

    def __ne__(self, other):
        return not self.desc == other.desc
```

Is this an acceptable change/fix? Or is there a better approach?

**Comment by elemoine** [comment]
Sounds good to me!
