### ISSUE TITLE
Support for returning rows as GeoJSON features

### ISSUE THREAD

**Issue by urschrei** [geoalchemy/geoalchemy2#249]
Recent versions of PostGIS (as of 3.0) support a way of calling [`ST_AsGeoJSON`](https://postgis.net/docs/ST_AsGeoJSON.html) with a record (row) as opposed to a geometry, is there a way of accomplishing this in GeoAlchemy2 by defining a `GenericFunction` that overrides the provided `func.ST_AsGeoJson`?

**Comment by adrien-berchet** [comment]
Hi, I am not sure to understand your use case, could you provide a minimal working example plz?

**Comment by elemoine** [comment]
More context here @adrien-berchet: https://groups.google.com/d/msg/sqlalchemy/owT52zKYNVw/iLYFSpynDQAJ. I agree that GeoAlchemy should support the record/feature version of ST_AsGeoJSON.

**Comment by adrien-berchet** [comment]
Ok I see. Looks tricky :)

**Comment by urschrei** [comment]
Yes, I suspected it might be, so I also asked Mike – I suspect my example is subtly wrong, but we'll wait and see.
