### ISSUE TITLE
Force 3D geometry on execute(ins)

### ISSUE THREAD

**Issue by nathanxmeyer** [geoalchemy/geoalchemy2#259]
I have looked through the documentation and code to see how to implement ST_Force3D when using Table to define geometry columns.  Is this possible and apologies if I missed it in the documentation somewhere.

Thank you.

**Comment by adrien-berchet** [comment]
If I correctly understand what you need, I think you can use the solution given in #219.

**Comment by nathanxmeyer** [comment]
Hello and thank you for the response.  I am using the programming model from the Core Tutorial and, because I am processing many tables of various definitions, setting the non-geometry table columns dynamically from a list generated from a JSON definition:

*(Column(name, String()) for name in l_fields))

 ... but defining my geometry columns manually:

Column('point', Geometry(geometry_type = 'POINT', srid = 32635, dimension = 3, management = True))

... then using insert() to create an insert object:

ins = newtable.insert().values(tablerow)

This all works and what I would like to be able to do is access the insert() object to wrap the geometry column insert statement with ST_Force3D.

I orginally used the programming model from the SQLite Tutorial but was not able to see a path to dynamically describing my table definitions (my Python skills are minimal, archaeologist, not programmer).

Is there a way to access the insert() and wrap the ST_GeomFromEWKT() so that it expresses like ST_Force3D(ST_GeomFromEWKT())

Thank you very much for the help.

**Comment by adrien-berchet** [comment]
Ok, I think the following should do it:

``` python
from sqlalchemy import create_engine
from sqlalchemy import MetaData
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import func
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy.types import TypeDecorator
from geoalchemy2 import Geometry
from geoalchemy2 import shape


engine = create_engine('postgresql://gis:gis@localhost/gis', echo=True)
metadata = MetaData(engine)

Base = declarative_base(metadata=metadata)


class ThreeDGeometry(TypeDecorator):
    impl = Geometry

    def bind_expression(self, bindvalue):
        return func.ST_Force3D(self.impl.bind_expression(bindvalue))


class Point(Base):
    __tablename__ = "point"
    id = Column(Integer, primary_key=True)
    three_d_geom = Column(
        ThreeDGeometry(srid=32635, geometry_type="POINTZ", dimension=3))


metadata.drop_all(checkfirst=True)
metadata.create_all()

# Create new point instance
p = Point()
p.geom = "SRID=4326;POINT(5 45)"
p.three_d_geom = "SRID=32635;POINT(5 45)"  # Insert a 2D geometry into a 3D column

# Create session
Session = sessionmaker(bind=engine)
session = Session()

# Insert point
session.add(p)
session.commit()

# Reset session
session = Session()

# Query the point and check the result
pt = session.query(Point).one()
pt_shape = shape.to_shape(pt.three_d_geom)
assert pt.three_d_geom.srid == 32635
assert pt_shape.wkt == "POINT Z (5 45 0)"
```

**Comment by nathanxmeyer** [comment]
Thank you very much.  I will attempt to use this while also dynamically building my class definitions.   That was the path I was on but Type(mytableclass, (Base, ), myattrdict) resulted in SQLAlchemy giving me an error saying it could not assign a primary key (which was defined in myattrdict) but perhaps I was doing something wrong.  Anyway, thank you the help; I will give it a try.

**Comment by adrien-berchet** [comment]
@nathanxmeyer I close this issue for now but don't hesitate to reopen it if you need more help.
