### ISSUE TITLE
alembic missing 'import geoalchemy2.types'

### ISSUE THREAD

**Issue by dazza-codes** [geoalchemy/geoalchemy2#261]
Using Flask-Migrate with:
```python

class Lake(db.Model):
    __tablename__ = "lakes"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    geom = db.Column(Geometry(geometry_type="POLYGON", srid=4326))
```

After `flask db migrate` and `flask db upgrade` to apply it results in:
```
  File "/home/joe/src/geo-app/migrations/versions/5c440397c82e_.py", line 27, in upgrade
    geoalchemy2.types.Geometry(geometry_type="POLYGON", srid=4326),
NameError: name 'geoalchemy2' is not defined
```

The migration seems OK, it's just missing an import, so it needs to be like:

```python

# THIS IMPORT IS MISSING from the auto-generated migration script
import geoalchemy2.types

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lakes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(geometry_type="POLYGON", srid=4326),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("spatial_ref_sys")
    # ### end Alembic commands ###
```

Have I missed something in the docs?  Is there an easy way to set a configuration somewhere so this just works every time?

**Comment by adrien-berchet** [comment]
Hi @dazza-codes 
Indeed the import is required but I can't see what we can do for it here. I think this issue should be submitted to the Flask-Migrate team.

**Comment by pmav99** [comment]
if you deal with a lot of Geometry columns, a quick workaround is to add `import geoalchemy2.types` in `script.py.mako`. This way all your migrations will have this line. Admittedly, a useless import is not so clean, but it is also not the end of the world (+ you can manually remove it if it annoys your linter)

**Comment by adrien-berchet** [comment]
I think we can closer this as it does not seem to be directly related to `geoalchemy2`.
Feel free to reopen if you need more help about it.
