### ISSUE TITLE
Cannot insert Raster from Select in 0.8.2

### ISSUE THREAD

**Issue by KeeganShaw-GIS** [geoalchemy/geoalchemy2#269]
Following changes in 0.8.0 inserting from select will fail with programming error.

> (psycopg2.ProgrammingError) can't adapt type 'RasterElement'

For example (using Flask-SQLAlchemy==2.4.1):
```
class DEM(db.Model):
    __tablename__ = 'dem'
    rid = db.Column(db.Integer, primary_key=True)
    rast = db.Column(Raster)
class repo_DEM(db.Model):
    __tablename__ = 'repo_dem'
    rid = db.Column(db.Integer, primary_key=True)
    rast = db.Column(Raster)

q = db.session.query(db_m.DEM.rast).first()
inst = db_m.repo_DEM(aoi_id = 1, rast = q.rast)
db.session.add(inst)
db.session.commit()
```

**Comment by adrien-berchet** [comment]
Hi @KeeganShaw-GIS 
Thanks for this report, we changed a lot of internal things in Raster and RasterElement classes and indeed I missed something during these changes.
#270 should fix this issue, could you please test it before I merge please?
