### ISSUE TITLE
How to use the new RasterElement?

### ISSUE THREAD

**Issue by Fenrihr** [geoalchemy/geoalchemy2#277]
Hello!

I want to use the Raster part of Geoalchemy but I ran into a problem: I cannot determine what is the type of data I have in RasterElement and how to convert it to a Numpy Array directly.

The only solution I found is to use Rasterio but it requires re-querying to get data that I already have:
```python
import sqlalchemy.orm as sao
import geoalchemy2 as geosa
import rasterio

engine = sa.create_engine(DB_URI, echo=False)

BaseEntity = declarative_base()
metadata = BaseEntity.metadata

db_maker = sao.sessionmaker(autocommit=False, autoflush=False, bind=engine)

class RasterToPgSQL(BaseEntity):
    __tablename__ = 'raster_to_pgsql'

    rid = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    rast = sa.Column(geosa.Raster())

session = db_maker()

# a row
a_row = session.query(RasterToPgSQL).filter(RasterToPgSQL.rid == 1).one()

# and for plot and make use of the raster data i need to do the following
import tempfile
from rasterio import plot
from geoalchemy2 import func

# data es memoryview
data = session.query(func.ST_AsTIFF(RasterToPgSQL.rast,'GTiff')).filter(RasterToPgSQL.rid == a_row.rid).scalar()

# this way also work
#data = db.session.query(func.ST_AsTIFF(a_row.rast.data, 'GTiff')).scalar()

# https://rasterio.readthedocs.io/en/latest/topics/memory-files.html
with tempfile.NamedTemporaryFile() as tmpfile: 
    tmpfile.write(data)
    
    with rasterio.open(tmpfile.name) as dataset:
        plot.show(dataset, cmap='viridis')
        
        data_array = dataset.read()
        print(data_array)  # Numpy data

```
any sugestion?

> Versions:
> - `sqlalchemy` == 1.3.17
> - `geoalchemy2` == 0.8.3
> - `rasterio` == 1.1.0

**Comment by adrien-berchet** [comment]
Hi @Fenrihr 
The `RasterElement` objects store the rasters using a WKB representation.
If you don't want to convert it in another format (like TIFF, PNG or whatever), I suggest you to use the solution described here: https://gis.stackexchange.com/a/131367/127797
I will try to add it in the [Gallery](https://geoalchemy-2.readthedocs.io/en/latest/gallery/index.html#gallery) later.

**Comment by Fenrihr** [comment]
Thanks you @adrien-berchet !!
I thought there was a solution already coded. I will read the material you passed.

It would be great if you add examples related to Raster to the Gallery.

**Comment by adrien-berchet** [comment]
@Fenrihr I added an example in the gallery.
