### ISSUE TITLE
ST_Union for Rasters using ORM without losing ST_Union for Geometry

### ISSUE THREAD

**Issue by micahjohnson150** [geoalchemy/geoalchemy2#284]
I am attempting to make a raster by joining two together using ORM. I see that GeoAlchemy2 has ST_Union defined for geometry. If I overwrite the function using my own I can use ST_Union for joining rasters which is awesome but I get the warning that I am overwriting the already registered ST_Union in the library.  I would rather not lose that ST_Union for geometry but I am unsure how to subclass this without losing it. 

Is there a way to rename it such that it doesn't overwrite the original? I tried renaming the class as follows:

``` python
class ST_RasterUnion(gfunc.GenericFunction):
    name = 'ST_Union
    type = Raster
```

Then I can use it as:

```python
raster = session.query(ST_RasterUnion(RasterData.raster)).all()
```
But I still get the warning below: 

```bash
SAWarning: The GenericFunction 'st_union' is already registered and is going to be overriden.
```

**Comment by adrien-berchet** [comment]
Hi @micahjohnson150 
Indeed, a few `PostGIS` functions can be applied to both `Geometry` and `Raster` but `geoalchemy2` can not handle this and thus these functions are only defined for `Geometry`.
As far as I know, the only solution to handle this is the one described here: https://geoalchemy-2.readthedocs.io/en/latest/gallery/test_raster_transform.html#sphx-glr-gallery-test-raster-transform-py
In your case, the query would become:
``` python
raster = session.query(sqlalchemy.func.ST_Union(RasterData.raster, type_=Raster)).all()
```
If it works in your case, I will add a few words in the `Raster` doc.

**Comment by micahjohnson150** [comment]
Ah, that will definitely work. I remember looking at that example but obviously didn't notice the union. Thanks!

**Comment by adrien-berchet** [comment]
Perfect. I will update the doc to make it more explicit.
