### ISSUE TITLE
Please consider adding the __version__ attribute.

### ISSUE THREAD

**Issue by apiszcz** [geoalchemy/geoalchemy2#288]
__version__ is a python package convention to indicate the current version.

**Comment by adrien-berchet** [comment]
Hi @apiszcz 
The `__version__` attribute was added in `geoalchemy2==0.8.3`, aren't you using an older version?

**Comment by apiszcz** [comment]
the test was, yes thx

**Comment by adrien-berchet** [comment]
You welcome :-)
