### ISSUE TITLE
How do you insert a raster into a table

### ISSUE THREAD

**Issue by carlostighe** [geoalchemy/geoalchemy2#290]
Given a `.tif` how do you insert it into a table.

```
class Activity(Base):
    __tablename__ = 'activity'
    id = Column(Integer, primary_key=True)
    rast = Column(Raster)

    def __init__(self, rast):
        self.rast = rast
```

**Comment by adrien-berchet** [comment]
Hi @carlostighe 

`GeoAlchemy2` can only process `Raster` objects using their WKB representation (the internal PostGIS representation).

If you want to insert data from a TIF file, I think that the most easy way to achieve this is to use the `raster2pgsql` script: https://postgis.net/docs/using_raster_dataman.html#RT_Raster_Loader.
Another way could be to use the `ST_FromGDALRaster` function but I never tried it (check this: https://gis.stackexchange.com/questions/129995/importing-geotiff-into-postgis-without-raster2pgsql).

Another tricky way could be to cypher the TIF into WKB manually, i.e. the opposite of this:
https://geoalchemy-2.readthedocs.io/en/latest/gallery/test_decipher_raster.html#sphx-glr-gallery-test-decipher-raster-py

There might be other libraries to do it but I don't know them.

**Comment by JanisGailis** [comment]
Adding a comment here for other people who might be struggling with this.

I ended up subclassing the `Raster` class and overriding the `bind_expression` method, like so:

```python
from geoalchemy2 import Raster

class GDALRaster(Raster):
    def bind_expression(self, bindvalue):
        return func.ST_FromGDALRaster(bindvalue)

class MyModel(Base):
    __tablename__="some_name"
    raster_data = Column(GDALRaster)
```
The `raster_data` column now expects to be built from a byte array, so, given a `.tif` file:
```python
with open(path, 'rb') as geotiff_file:
    model.raster_data = geotiff_file.read()
```
Saving into the DB now works as expected. I haven't yet tested if this introduces some problems down the road (not expecting it though). Also, the geotiffs I have to work with are rather small (some megabytes), I'm not entirely sure this data ingestion method is well suited for large rasters.

**Comment by adrien-berchet** [comment]
Thanks for this snippet @JanisGailis !
The only issue I can see with this solution is that a selected Raster object can not be re-inserted as is, which can be weird if the user is not aware of that.

**Comment by JanisGailis** [comment]
I initially thought of adding a symmetrical `column_expression` with `ST_AsGDALRaster` or `ST_AsTIFF`. But I think this would imply that a selected object could not then further be used in PostGIS pipelines. Is this right?

Do you have any other suggestions apart from what's already mentioned above?

And thanks a lot for maintaining this project! :+1:

**Comment by adrien-berchet** [comment]
Indeed this could be a more robust solution. To my knowledge, `column_expression` is only used for the last element of the pipeline. And pipelines ending by selecting a `Raster` are quite unusual, so that should not be an issue.

**Comment by chenyhsu** [comment]
> Adding a comment here for other people who might be struggling with this.
> 
> I ended up subclassing the `Raster` class and overriding the `bind_expression` method, like so:
> 
> ```python
> from geoalchemy2 import Raster
> 
> class GDALRaster(Raster):
>     def bind_expression(self, bindvalue):
>         return func.ST_FromGDALRaster(bindvalue)
> 
> class MyModel(Base):
>     __tablename__="some_name"
>     raster_data = Column(GDALRaster)
> ```
> 
> The `raster_data` column now expects to be built from a byte array, so, given a `.tif` file:
> 
> ```python
> with open(path, 'rb') as geotiff_file:
>     model.raster_data = geotiff_file.read()
> ```
> 
> Saving into the DB now works as expected. I haven't yet tested if this introduces some problems down the road (not expecting it though). Also, the geotiffs I have to work with are rather small (some megabytes), I'm not entirely sure this data ingestion method is well suited for large rasters.

For other people who encountered  `NameError: name 'func' is not defined`, Add `from sqlalchemy.sql import func`.

Have used this snippet to upload GeoTiff with about 700 Mib in size, works like a charm.
