### ISSUE TITLE
Symbol not found: _GEOSArea

### ISSUE THREAD

**Issue by schmidtfx** [geoalchemy/geoalchemy2#301]
Hi, 

I'm getting the following error on MacOS. I'm trying to load the spatialite extension:

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) dlopen(mod_spatialite.dylib, 10): Symbol not found: _GEOSArea

Any ideas?

Thanks

**Comment by adrien-berchet** [comment]
Hi @schmidtfx 
No idea, sorry.
I don't think it is directly related to `GeoAlchemy2`, it is probably due to a broken install of spatialite. You should try to ask on their side.

**Comment by adrien-berchet** [comment]
No more activity here, but feel free to reopen if needed.
