### ISSUE TITLE
Functions returning NULL instead of element data

### ISSUE THREAD

**Issue by jwtrhs** [geoalchemy/geoalchemy2#310]
I believe this is the source of the problem in #151

We have the following failing test in our code:

```python
wkb = from_shape(box(1, 1, 2, 2), srid=4326)
query = session.query(GeoTable).filter(func.ST_INTERSECTS(Catchment.geometry, wkb))

assert query.sql == (
    "SELECT geotable.id \n"
    "FROM geotable \n"
    "WHERE ST_Intersects(geotable.geometry, '0103000000010000000500000000000000000"
    "00040000000000000f03f00000000000000400000000000000040000000000000f03f000000000"
    "0000040000000000000f03f000000000000f03f0000000000000040000000000000f03f')"
)
```

which fails on the WHERE clause because `query.sql` returns `WHERE ST_Intersects(catchment.geometry, ST_GeomFromWKB(NULL, 4326))`. Note the `NULL` inside the `ST_GeomFromWKB` function instead of embedding the hex string for `wkb`.

I *think* the cause of this issue is that the function code is using the `WKBElement.data` attribute, which is a `buffer` type but I think it is expecting a string. Maybe the function code should be using the `WKBElement.desc` attribute instead? (e.g. [here](https://github.com/geoalchemy/geoalchemy2/blob/a7df39a9bf8798eec764a710bdfed15a7f2ac6cb/geoalchemy2/functions.py#L190)). This only effects the `WKBElement` type, as `WKTElement.data` is already a string.

If I hack the test to set the `wkb.data` attribute to `wkb.desc`, it apparently works as intended.

**Comment by adrien-berchet** [comment]
Hi @jwtrhs 
Thanks for your report.
I have a few questions:
1. what is your version of `sqlalchemy`? Because upper case functions like `func.ST_INTERSECTS` could be an issue before `sqlalchemy < 1.3.4`.
2.what is `Catchment` in your query?

I tried to add the following test in `geoalchemy2/tests/test_functional.py`:
``` python
    def test_filter_from_wkb(self):
        from shapely.geometry import box
        wkb = from_shape(box(1, 1, 2, 2), srid=4326)
        query = session.query(Poi.id).filter(func.ST_INTERSECTS(Poi.__table__.c.geom, wkb))

        conn = session.connection()
        cur = conn.connection.cursor()
        compiled = query.statement.compile(conn)
        raw_sql = cur.mogrify(str(compiled), compiled.params)
        assert raw_sql == (
            b"SELECT gis.poi.id \n"
            b"FROM gis.poi \n"
            b"WHERE ST_Intersects(gis.poi.geom, ST_GeomFromWKB("
            b"'\\x010300000001000000050000000000000000000040000000000000f03f0000000000000040000000"
            b"0000000040000000000000f03f0000000000000040000000000000f03f000000000000f03f0000000000"
            b"000040000000000000f03f'::bytea, 4326))"
        )
```
And it works fine for me.

**Comment by jwtrhs** [comment]
Hi @adrien-berchet,

Apologies for the incomplete bug report, here's a better example:

```python
from geoalchemy2.shape import from_shape
from geoalchemy2.types import Geometry
from shapely.geometry import box
from sqlalchemy import Column, func, Integer
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Geotable(Base):
    __tablename__ = 'geotable'
    id = Column(Integer, primary_key=True)
    geometry = Column(Geometry)

wkb = from_shape(box(1, 1, 2, 2), srid=4326)

f = func.ST_INTERSECTS(Geotable.geometry, wkb)

print(f.compile(compile_kwargs={'literal_binds': True}))
```

This prints the result:
```
ST_Intersects(geotable.geometry, ST_GeomFromWKB(NULL, 4326))
```

This is using the latest versions in pip of SQLAlchemy, GeoAlchemy2 and Shapely on Python 3.9.1:
```
GeoAlchemy2==0.8.4
Shapely==1.7.1
SQLAlchemy==1.3.23
```

**Comment by adrien-berchet** [comment]
Ok I see.
For a reason I don't remember, the compile method is not always able to return the actual query. In this case I think it is due to the type of the wkb data (`memoryview` type) that can not be properly compiled to str. Nevertheless, you can still get the `hex` value of the data given to the function with this: `print("wkb hex value =", list(list(f.clauses)[1].clauses)[0].value.hex())`. And when you use the function in a query it should be properly executed because the driver (usually psycopg2) is able to process this.

**Comment by jwtrhs** [comment]
Thanks @adrien-berchet, yes I think you're right. It looks like SQLAlchemy doesn't know what to do with the `memoryview` or `buffer` when compiling it into an SQL string.

We've resolved the issue on our end by removing the need for the `literal_binds` string compilation and using the statement object instead, which is a better way to do it anyway.

Many thanks for looking into it!

**Comment by adrien-berchet** [comment]
Ok, good to know that you were able to solve your issue :-)
See you!
