### ISSUE TITLE
Wrong object type for ST_ValueCount ?

### ISSUE THREAD

**Issue by gilles-morain** [geoalchemy/geoalchemy2#315]
Hi, I'm a total newbie regarding GeoAlchemy, but I think there is an issue with the `ST_ValueCount` definition in `functions.py` as the return type should be a list of tuples, and not a raster. Banged my head against the wall until I manually changed `'ST_ValueCount', types.Raster` to `'ST_ValueCount', None` in my local virtual environment.

**Comment by adrien-berchet** [comment]
Hi @gilles-morain 
Indeed, you're right, sorry about that.
The ongoing PR #298 will fix this but I don't know when I will be able to finish it...

**Comment by adrien-berchet** [comment]
Should be fixed in 0.9.0 release.
