### ISSUE TITLE
Support for MySQL spatial queries

### ISSUE THREAD

**Issue by rtindru** [geoalchemy/geoalchemy2#318]
Hello, I am a new to the Geoalchemy community and just starting to understand spatial data types and querying. 

I noticed that Geoalchemy focused on PostGIS, and I wanted to use this issue to understand if there are plans to support MySQL spatial extensions in the future.

1. Are there plans to support MySQL in the future? Are there other packages that do this already?
2. Are there challenges to supporting MySQL spatial extensions that I should be aware of?
3. I am interested in contributing to the project by adding MySQL support, depending on 1 & 2  — would that be a useful addition to this project?

Look forward to learning more!

**Comment by adrien-berchet** [comment]
Hi @rtindru !

I don't know MySQL (I never used it) and there is no plan to support it (there is no plan at all actually :innocent:  ). It would indeed be great to support more types of DBMS. I am not aware of other packages to deal with it but I never looked for it.

I don't know if you already looked how `geoalchemy2` works but it is just an extension of `SQLAlchemy`. `SQLAlchemy` deals with all the DB access and stuff and `Geoalchemy2` only create specific types and functions for spatial data.
The spatial extensions of the DB (PostGIS, SpatiaLite, etc.) are usually based on the OGC specification, so they basically all have the same data types and functions. `Geoalchemy2` only defines the standard types and functions and then SQLAlchemy builds the queries for the DBMS in use, so `geoalchemy2` should theoretically work with any DBMS. In the real world, each spatial extension of the DBMS may have a few non-standard specific features, so in that case we have to add these specific features in `geoalchemy2`.
Currently, `geoalchemy2` works with `PostGIS` and `SpatiaLite` (from SQLite) so I guess we could add MySQL support, depending on how different it is from PostGIS. As far as I can see, they also follow the standard OGC specification so we should not need a lot of changes to make it work.
As a first test, you could just run the tests from `tests/test_functional.py` with a MySQL engine to see what is failing. You can paste the log here so we can try to help understand why it is failing and what kind of changes in `geoalchemy2` would be needed to make it work.

Anyway, thank you for this issue and your future contributions, neither @elemoine nor I have much time to work on this project at the moment so a new contributor would be great!

**Comment by rtindru** [comment]
@adrien-berchet Thank you for your response! I'd love to **try** to contribute MySQL support to this Geoalchemy with your and @elemoine's support. I am reasonably familiar with SQLAlchemy as it is similar to the Django ORM. However, I am just beginning to learn the GPS, spatial querying, PostGIS and the OGC specification.

As you correctly noted, many of the defined by PostGIS and provided by GeoAlchemy appear to exist in MySQL. I will start with the test functions and report back.

Very excited to meet you and be working on this!

**Comment by rtindru** [comment]
Hey team, I have an update! I setup the environment for GeoAlchemy with SQLAlchemy, MySQL-5.7, mysqlclient, and postgis.

I replaced the `create_engine` commands inside the test functions, and ran `py.test`. 

Here's the output from the test run:
```shell
(geoalch)  ✘ rajtilak.indrajit@it-admins-MacBook-Pro  ~/Code/geoalchemy2   master ±  py.test
============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.9.5, pytest-3.7.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/rajtilak.indrajit/Code/geoalchemy2, inifile:
plugins: cov-2.5.1
collected 325 items / 1 errors / 1 skipped

===================================================================================== ERRORS =====================================================================================
___________________________________________________________________ ERROR collecting tests/test_functional.py ____________________________________________________________________
../../Envs/geoalch/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1770: in _execute_context
    self.dialect.do_execute(
../../Envs/geoalch/lib/python3.9/site-packages/sqlalchemy/engine/default.py:717: in do_execute
    cursor.execute(statement, parameters)
../../Envs/geoalch/lib/python3.9/site-packages/MySQLdb/cursors.py:206: in execute
    res = self._query(query)
../../Envs/geoalch/lib/python3.9/site-packages/MySQLdb/cursors.py:319: in _query
    db.query(q)
../../Envs/geoalch/lib/python3.9/site-packages/MySQLdb/connections.py:259: in query
    _mysql.connection.query(self, query)
E   MySQLdb._exceptions.OperationalError: (1305, 'FUNCTION gis.PostGIS_Lib_Version does not exist')

The above exception was the direct cause of the following exception:
tests/test_functional.py:103: in <module>
    postgis_version = session.execute(func.postgis_lib_version()).scalar()
../../Envs/geoalch/lib/python3.9/site-packages/sqlalchemy/orm/session.py:1689: in execute
    result = conn._execute_20(statement, params or {}, execution_options)
../../Envs/geoalch/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1582: in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
../../Envs/geoalch/lib/python3.9/site-packages/sqlalchemy/sql/functions.py:131: in _execute_on_connection
    return connection._execute_function(
../../Envs/geoalch/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1267: in _execute_function
    return self._execute_clauseelement(
../../Envs/geoalch/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1451: in _execute_clauseelement
    ret = self._execute_context(
../../Envs/geoalch/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1813: in _execute_context
    self._handle_dbapi_exception(
../../Envs/geoalch/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1994: in _handle_dbapi_exception
    util.raise_(
../../Envs/geoalch/lib/python3.9/site-packages/sqlalchemy/util/compat.py:207: in raise_
    raise exception
../../Envs/geoalch/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1770: in _execute_context
    self.dialect.do_execute(
../../Envs/geoalch/lib/python3.9/site-packages/sqlalchemy/engine/default.py:717: in do_execute
    cursor.execute(statement, parameters)
../../Envs/geoalch/lib/python3.9/site-packages/MySQLdb/cursors.py:206: in execute
    res = self._query(query)
../../Envs/geoalch/lib/python3.9/site-packages/MySQLdb/cursors.py:319: in _query
    db.query(q)
../../Envs/geoalch/lib/python3.9/site-packages/MySQLdb/connections.py:259: in query
    _mysql.connection.query(self, query)
E   sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1305, 'FUNCTION gis.PostGIS_Lib_Version does not exist')
E   [SQL: SELECT PostGIS_Lib_Version() AS `PostGIS_Lib_Version_1`]
E   (Background on this error at: http://sqlalche.me/e/14/e3q8)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================= 1 skipped, 1 error in 0.94 seconds =======================================================================
```


I had two questions:
1. Can you help me understand this error, and how to get past it?
2. Since there was only one failure, does that mean the other 325 test passed, or were they interrupted? Is there some way to run other tests, or is this a blocker?

Look forward to tinkering with this and getting it to work!

**Comment by rtindru** [comment]
I manually set the `post_gis_version` and `post_gis_major_version` variables to `'1.3'1 and `1` and re-ran the tests. 
```python
postgis_version = '1.3'
postgres_major_version = 1
```

Pytest summary below!
```zsh
========================================================== 2 failed, 310 passed, 10 skipped, 45 error in 14.13 seconds ===========================================================
```

Attached the entire output as a logfile.
[pytest.log](https://github.com/geoalchemy/geoalchemy2/files/6664790/pytest.log)

**Comment by adrien-berchet** [comment]
Hello @rtindru !
Thanks for the log, it seems the issue here is due to the creation of the spatial indexes and to the management of the spatial columns.
I think it would be more convenient to create a PR with your changes so I can see them and even update them directly.

**Comment by adrien-berchet** [comment]
Hello @rtindru 
Do you need more help on this topic? Do you want me to create a draft PR to discuss it?

**Comment by hemna** [comment]
I just came across this extension to sqlalchemy and was bummed to learn that it doesn't support mysql/mariadb.   pgsql is just such a pain to use compared to mysql/mariadb.

**Comment by adrien-berchet** [comment]
Hi @hemna 
Indeed, MySQL is not supported at the moment, sorry for the disappointment.
There is a work in progress on that topic but it might take some time to be released (if it is, because I am afraid we might need deep changes in `geoalchemy2` to make it work)...

**Comment by adrien-berchet** [comment]
@rtindru 
I started a draft in #330 so we can talk about this.
