### ISSUE TITLE
schema in uppercase ignored in version 0.9.0 (worked fine with 0.8.5)

### ISSUE THREAD

**Issue by tomasjerabek-com** [geoalchemy/geoalchemy2#320]
Example:

`df.to_postgis(con=engine_postgis, name="tablename", schema="UPPERCASENAME")`

is converted to uppercasename.tablename and therefore fails as it cannot find the relevant schema (which is case sensitive). This exact code used to work in version 0.8.5 (case was kept).

Thanks for checking.

**Comment by adrien-berchet** [comment]
Hi @tomasjerabek-com 
Thanks for this report, I am surprised because I don't remember we changed anything that could have changed the case of the schema. Can you post the complete traceback of the exception please?
Also, are you sure this is not caused by a new version of psycopg2, geopandas or sqlalchemy?

**Comment by tomasjerabek-com** [comment]
Hi Adrien,

Thanks for taking care.

This code
`df.to_postgis(con=engine_postgis, name="tablename", schema="NDVI3", if_exists="replace")`

produces this with geoalchemy2==0.9.0:
                 
```
File "/Users/tomas/workspace/test_project/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) schema "ndvi3" does not exist

[SQL: CREATE INDEX idx_tablename_geometry ON NDVI3.tablename USING GIST (geometry)]
(Background on this error at: http://sqlalche.me/e/14/f405)
```

===
Exact same code right after downgrading to geoalchemy2==0.8.5 works just fine and "tablename" is created under the desired schema "NDVI3".
No other packages were changed/downgraded.

 ```
% pip install geoalchemy2==0.8.5
Collecting geoalchemy2==0.8.5
  Using cached GeoAlchemy2-0.8.5-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: SQLAlchemy>=1.1 in ./venv/lib/python3.9/site-packages (from geoalchemy2==0.8.5) (1.4.17)
Requirement already satisfied: greenlet!=0.4.17 in ./venv/lib/python3.9/site-packages (from SQLAlchemy>=1.1->geoalchemy2==0.8.5) (1.1.0)
Installing collected packages: geoalchemy2
  Attempting uninstall: geoalchemy2
    Found existing installation: GeoAlchemy2 0.9.0
    Uninstalling GeoAlchemy2-0.9.0:
      Successfully uninstalled GeoAlchemy2-0.9.0
Successfully installed geoalchemy2-0.8.5

```

**Comment by adrien-berchet** [comment]
I got it, indeed we forgot some quotes in index creation, sorry about that.
#321 should fix this, can you test it please?

**Comment by tomasjerabek-com** [comment]
Seems to work fine. Thanks @adrien-berchet 👍

**Comment by adrien-berchet** [comment]
Version 0.9.1 is now released with this fix.
