### ISSUE TITLE
BigQuery GEOGRAPHY support

### ISSUE THREAD

**Issue by jimfulton** [geoalchemy/geoalchemy2#323]
I'm working on integrating GeoAlchemy2 with BigQuery.  

It partly works out of the box.

**Comment by adrien-berchet** [comment]
Hi @jimfulton 
Good to know, thanks!
If some specific tweaks are needed in geoalchemy2 a PR is welcome :)

**Comment by jimfulton** [comment]
Thanks!

**Comment by jimfulton** [comment]
@adrien-berchet can I get your read on #328?

If you're cool with that approach, then I'll add tests and finish the BigQuery side of things.

The alternative would be to subclass GEOAlchemy classes, which I'd prefer not to do for various reasons.

Later there will be a follow on PR to add support for tracking argument types in geographic (`ST_...`) functions to get conversion of string arguments. PostGIS automatically coverts string arguments to geography, but BigQuery doesn't.

**Comment by jimfulton** [comment]
t turns out that the main advantage I was hoping for by not subclassing doesn't exist.

Still, the subclassing approach hides geoalchemy2 somewhat, which is a disadvantage, IMO.

OTOH, subclassing makes changes to geoalchemy2 unnecessary, which is an advantage.

I'm interested in your thoughts. :)

**Comment by adrien-berchet** [comment]
As stated in #328 , it seems more relevant to subclass in `sqlalchemy-bigquery`.
