### ISSUE TITLE
Support for composite type summarystats

### ISSUE THREAD

**Issue by nathanlcarlson** [geoalchemy/geoalchemy2#333]
I'm not sure how it would work, but could support be added for this type? Currently required to parse the returned string.
https://postgis.net/docs/summarystats.html

**Comment by adrien-berchet** [comment]
Hi @nathanlcarlson 
It is quite easy to add it, there is an example in the gallery: https://geoalchemy-2.readthedocs.io/en/latest/gallery/test_summarystatsagg.html#sphx-glr-gallery-test-summarystatsagg-py
But I will add it in #334 so it is easily available for everyone.

**Comment by nathanlcarlson** [comment]
@adrien-berchet  Excellent! Thank you for your work on this library.

**Comment by adrien-berchet** [comment]
You're welcome :)

**Comment by nathanlcarlson** [comment]
Hi @adrien-berchet , I got around to adding this to my code manually. I added these two classes:
```
class SummaryStats(CompositeType):
     """Define the composite type returned by the function ST_SummaryStatsAgg"""
     typemap = {
         'count': Integer,
         'sum': Float,
         'mean': Float,
         'stddev': Float,
         'min': Float,
         'max': Float,
     }

class ST_SummaryStatsAgg(GenericFunction):
    type = SummaryStats
```
And followed the composite example in the gallery in the docs.
I found I would get the following error when user ST_SummaryStatsAgg
```
...
KeyError: "Type 'SummaryStats()' doesn't have an attribute: '__iter__'"
```
I tracked it down to the comparator_factory class within CompositeType and found the following modified version worked:
```
     class comparator_factory(UserDefinedType.Comparator):
        def __getattr__(self, key):
            try:
                return getattr(self.type.typemap, key)
            except AttributeError:
                pass
            try:
                type_ = self.type.typemap[key]
            except KeyError:
                raise KeyError("Type '%s' doesn't have an attribute: '%s'"
                            % (self.type, key))
            return CompositeElement(self.expr, key, type_)
```
This may or may not be the correct way to address this, just wanted to bring it up and see if I am either missing something or contribute this fix.
For reference:
```
$ python --version
Python 3.9.6
$ pip freeze |grep emy
GeoAlchemy2==0.9.4
SQLAlchemy==1.4.25
```

**Comment by adrien-berchet** [comment]
Hi @nathanlcarlson 
Thank you for your report. Could you provide a minimal reproducible example that I can test? Especially with the query you used, because the one provided in the gallery works for me locally and in the CI.

**Comment by nathanlcarlson** [comment]
After review, I realize now that I had a slight difference:
```
q = select(
    Raster.rast.ST_SummaryStatsAgg(1, True).label('stats')
).where(
    Raster.object_id == id
)
```
instead of 
```
q = select(
    [Raster.rast.ST_SummaryStatsAgg(1, True).label('stats')]
).where(
    Raster.object_id == id
)
```
Making the select a list fixes the error. I don't really have a problem with that, but it could trip up any one using this that doesn't know that.

**Comment by nathanlcarlson** [comment]
Looking deeper I see this has to do with the initialization of the select. It checks hasattr({item being selected}, '__iter__'), which relies on __getattr__ raising an AttributeError to indicate hasattr == False. Using this idea I tested the following change, making KeyError into AttributeError:
```
     class comparator_factory(UserDefinedType.Comparator):
        def __getattr__(self, key):
            try:
                type_ = self.type.typemap[key]
            except KeyError:
                raise AttributeError("Type '%s' doesn't have an attribute: '%s'"
                            % (self.type, key))
            return CompositeElement(self.expr, key, type_)
```
Does that seem like a decent pattern?

**Comment by nathanlcarlson** [comment]
Also for more context, my sqlalchemy set up:
```
engine = create_engine(
    SQLALCHEMY_DATABASE_URL, future=True
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()
```

**Comment by adrien-berchet** [comment]
I was able to reproduce your issue and indeed, changing the `KeyError` into `AttributeError` in the `comparator_factory` is probably the best solution. 

@zzzeek could you confirm it is the best way to fix this? Here is a summary:
The query
```python
select([Ocean.rast.ST_SummaryStatsAgg(1, True).label("stats")])
```
works properly while the query (without the `[...]`)
```python
select(Ocean.rast.ST_SummaryStatsAgg(1, True).label("stats"))
```
fails with the following exception:
```python
*** KeyError: "Type 'SummaryStats()' doesn't have an attribute: '__iter__'"
```
which is raised here: https://github.com/geoalchemy/geoalchemy2/blob/master/geoalchemy2/types.py#L373
We propose to change the `KeyError` into `AttributeError` so that it can be caught by `select` (here: https://github.com/sqlalchemy/sqlalchemy/blob/6206f0ff74e95c9339dc0f0e26caab55e9bcda45/lib/sqlalchemy/sql/selectable.py#L5203). WDYT?

**Comment by zzzeek** [comment]
oh absolutely, `__getattr__` should only raise AttributeErrors

**Comment by adrien-berchet** [comment]
Ok, let's do this then. Thank you very much!

**Comment by adrien-berchet** [comment]
@nathanlcarlson can you check that everything is fine for your use case with the master branch please?

**Comment by nathanlcarlson** [comment]
Hi, yep, it works as expected. Thank you!

**Comment by adrien-berchet** [comment]
Ok perfect. Thank you very much for your detailed report.
Do you need a new release with this feature?

**Comment by nathanlcarlson** [comment]
We are fine with our override in place. No need to release another version until the project wants to.

**Comment by adrien-berchet** [comment]
Ok, fine. See you later then :)
