### ISSUE TITLE
Performance warning with SQLAlchemy 1.4.28

### ISSUE THREAD

**Issue by mbtronics** [geoalchemy/geoalchemy2#336]
Got a couple of these after updating to SQLAlchemy 1.4.28:

SAWarning: Class **ST_AsGeoJSON** will not make use of SQL compilation caching as it does not set the 'inherit_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this object can make use of the cache key generated by the superclass.  Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)

Also got it for **ST_Contains** .

**Comment by adrien-berchet** [comment]
Hi @mbtronics 
Indeed, I can reproduce these warnings when I run the tests, thank you for the report.
I will try to fix this in #338

**Comment by mbtronics** [comment]
thanks!

**Comment by adrien-berchet** [comment]
Hi @mbtronics 
The branch of #338 should be ready now, could you test it on your use case before I merge please?

**Comment by mbtronics** [comment]
I'll have a look at it, thanks!

**Comment by mbtronics** [comment]
Can't notice any differences performance wise and the warnings are gone.

**Comment by adrien-berchet** [comment]
Thank you very much @mbtronics , let's merge this!
