### ISSUE TITLE
sqlalchemy.exc.StatementError: (builtins.TypeError) %d format: a number is required, not str

### ISSUE THREAD

**Issue by gsbaby** [geoalchemy/geoalchemy2#341]
Hello, maybe my English is not good！
When I use geopandas.GeoDataFrame.to_sql, I need to define：
```
dtype={
  'geometry': Geometry(geometry_type='GEOMETRY', srid=spatial_ref)
}
```
using from geoalchemy2 import Geometry
Found that 'types.py' reported a data type error.
```
File "E:\ProgramData\Python37\lib\site-packages\geoalchemy2\types.py", line 186, in process
    return 'SRID=%d;%s' % (bindvalue.srid, bindvalue.data)
sqlalchemy.exc.StatementError: (builtins.TypeError) %d format: a number is required, not str
```
![667F3B5A-489A-4a77-8632-387710A7F73A](https://user-images.githubusercontent.com/9951820/147624004-dff862f0-e4b2-460b-b1bb-33d64b491083.png)

After inspection, it is found that str type data appears in the place where'%d' needs to be added in 'types.py'.
For example, in line 186 of 'type.py': 
`return'SRID=%d;%s'% (bindvalue.srid, bindvalue.data)`

I think it needs to be modified to: 
`return'SRID=%d;%s'% (int(bindvalue.srid ), bindvalue.data)`

And after the modification is completed, it can be executed normally.

**Comment by adrien-berchet** [comment]
Hello @gsbaby 

Thank for your report. Could you provide a complete working example please? I am wondering how you end up with WKTElement objects here.

In your example, what is the type of the variable `spatial_ref`? Isn't it a `str` instead of an `int`?

For your proposed fix, you could also just write `return 'SRID=%s;%s' % (bindvalue.srid, bindvalue.data)`, so the query construction is more permissive and the error will be raised by the DB if it there is an issue.

**Comment by gsbaby** [comment]
```
import geopandas as gpd
from sqlalchemy import create_engine
from geoalchemy2 import Geometry, WKTElement
import os
def shp2pgsql(file, engine):
    """单个shp文件入库"""
    file_name = os.path.split(file)[1]
    print('正在写入:' + file)
    tbl_name = file_name.split('.')[0]  # 表名
    map_data = gpd.GeoDataFrame.from_file(file)

    spatial_ref = map_data.crs.srs.split(':')[-1]  # 读取shp的空间参考

    map_data['geometry'] = map_data['geometry'].apply(
        lambda x: WKTElement(x.wkt, spatial_ref))
    # geopandas 的to_sql()方法继承自pandas, 将GeoDataFrame中的数据写入数据库
    map_data.to_sql(
        name=tbl_name,
        con=engine,
        if_exists='replace',# {'fail', 'replace', 'append'}, default ‘fail'
        chunksize=1000,  # 设置一次入库大小，防止数据量太大卡顿
        # 指定geometry的类型,这里直接指定geometry_type='GEOMETRY'，防止MultiPolygon无法写入
        dtype={'geometry': Geometry(
            geometry_type='GEOMETRY', srid=spatial_ref)},
        method='multi'
    )
```
Awesome, you are right, it is a str instead of an int. And I changed it back. Thanks a lot!
`spatial_ref = map_data.crs.srs.split(':')[-1]  # 读取shp的空间参考`

**Comment by gsbaby** [comment]
can you check out where I can optimize it? Please!

**Comment by adrien-berchet** [comment]
Ah cool. I guess we should check the type of the SRID given to define the column, so it fails earlier and in a more understandable way. I will try to do this.

For your optimization issue, I would say that you should not use GeoAlchemy2 if you want to process many geometries :-)
Nope that you should not use the `to_sql` method either, it is very slow. The fastest way to insert new geometries from Shapely objects (the ones stored in the `geometry`column of your DataFrame) is to cast them into raw WKT or WKB (with  `df["geometry"].to_wkb()`) and to create a specific query that uses the `ST_GeomFromWKB` function from PostGIS).

**Comment by gsbaby** [comment]
> Ah cool. I guess we should check the type of the SRID given to define the column, so it fails earlier and in a more understandable way. I will try to do this.
> 
> For your optimization issue, I would say that you should not use GeoAlchemy2 if you want to process many geometries :-) Nope that you should not use the `to_sql` method either, it is very slow. The fastest way to insert new geometries from Shapely objects (the ones stored in the `geometry`column of your DataFrame) is to cast them into raw WKT or WKB (with `df["geometry"].to_wkb()`) and to create a specific query that uses the `ST_GeomFromWKB` function from PostGIS).

Yeah, thank you very much!

**Comment by gsbaby** [comment]
:-)

**Comment by adrien-berchet** [comment]
You're welcome :)
