### ISSUE TITLE
Question: Is there a best practices way to support TypeDecorator classes?

### ISSUE THREAD

**Issue by ryangooch** [geoalchemy/geoalchemy2#342]
I currently use two database backends for a project that I'm working on: postgresql and sqlite. I've been attempting to use geoalchemy2 to help add geospatial support to my application. I would like to design a custom type for a geospatial column using sqlalchemy's `TypeDecorator` methodology, where the implementation is based on geoalchemy2's `Geometry` class, but that can specify a `Geography` class as column type in the case where I'm connecting to or creating a geospatial column in a table with postgis.

Taking a look at the code, I see that geoalchemy2's `__init__.py` sets up a series of event handlers for managing addition of `Geometry` columns in a database. However, it requires the Column to be specified as a `Geometry` column specifically in order to correctly handle the geospatial column (in the case of sqlite), and fails to catch the custom typed class column as being a geospatial column.

One idea that I had to allow my `TypeDecorator` custom type class to be "seen" as a GIS type column is to essentially remove the events that are created in geoalchemy2's `__init__.py`, copy the event setup functions to my own script, add functionality so that the custom type class is seen as GIS type, then re-run the event handlers. However, this feels brittle and unsustainable in the long run. 

Is there a better method that would be recommended for a case like this? Maybe something using the custom type class itself?

An example of the sort of custom type class I would like to use is shown below.

```python
import sqlalchemy as sa
from geoalchemy2.types import Geography, Geometry
from geoalchemy2.shape import to_shape
from sqlalchemy.ext.declarative import declarative_base

class HybridGeospatial(sa.types.TypeDecorator):
    """
    Column type for Geospatial data points in geodetic point coordinates (longitude, latitude).
    """
    impl = Geometry
    
    def load_dialect_impl(self, dialect):
        if dialect.name == 'postgresql':
            return dialect.type_descriptor(Geography)
        else:
            return dialect.type_descriptor(Geometry)

    def process_bind_param(self, coords, dialect):
        """
        Take a tuple or 2-D array `coords` representing lon/lat coordinates, and return WKT
        """
        if coords is None:
            return coords
        if len(coords) != 2:
            raise TypeError("Incorrect length for bound parameter of type HybridGeospatial")

        return f"POINT ({coords[0]} {coords[1]})"

    def process_result_value(self, result_wkb, dialect):
        """
        Result value will be in well-known binary format
        """
        if result_wkb is None:
            return result_wkb

        return to_shape(result_wkb).centroid.coords[0]


Base = declarative_base()

class GeoTable(Base):
    __tablename__ = 'geo_table'
    id = sa.Column(sa.Integer, primary_key=True)
    geom = sa.Column(HybridGeospatial(geometry_type='POINT', management=True, dimension=2))

GeoTable.__table__.create(engine)
```

Thanks in advance for any help!

**Comment by adrien-berchet** [comment]
Hi @ryangooch !
Thank you for your report, you are right, there is an issue when using `TypeDecorator`. I made a fix attempt in #343 , could you check it works for your use case please?

**Comment by ryangooch** [comment]
Hi @adrien-berchet , thanks for the quick response! I've tested the branch you created in #343 and it appears to work perfectly with the `TypeDecorator` class. Thanks!

**Comment by adrien-berchet** [comment]
Cool, thank you for testing.
I am going to merge it, do you need a new release?

**Comment by ryangooch** [comment]
A new release would definitely be the most convenient for me. Thanks again for your help!

**Comment by adrien-berchet** [comment]
The new release is up: https://github.com/geoalchemy/geoalchemy2/releases/tag/0.10.1

**Comment by ryangooch** [comment]
Hello again @adrien-berchet . I've had some more time to dive into the implementation for this and discovered another small issue, I think. Basically, the type checking logic should look at the result of the `TypeDecorator.load_dialect_impl()` class method instead of the `impl` class attribute (if I understand it correctly).

An example, based on the above code, might look like this:

```python
from sqlalchemy import create_engine
engine = create_engine('postgresql://scott:tiger@localhost:5432/mydatabase')

[...]

tested_type = GeoTable.geom.type
print(tested_type.impl)
# Geometry(geometry_type='POINT', srid=4326, management=True, from_text='ST_GeomFromEWKT', name='geometry')
print(tested_type.load_dialect_impl(engine.dialect))
# Geography(geometry_type='POINT', srid=4326, management=True, from_text='ST_GeogFromText', name='geography')
```

Since the former is used, in this example, the `Geography` column is never used, and the column is treated like a `Geometry` column regardless of the database dialect. What do you think?

Thanks!

**Comment by adrien-berchet** [comment]
Hi again @ryangooch :)
According to the doc, it seems you are right. Sorry about that, I didn't know that `load_dialect_impl()` method.
Can you confirm that #346 finally solves your issue properly please?

**Comment by ryangooch** [comment]
Hello @adrien-berchet , thanks for the quick work! I've checked this with both `Geography` and `Geometry` on databases using postgresql and sqlite, respectively, and it works as expected. Apologies for not catching the `load_dialect_impl()` issue before - I should have tested more thoroughly. 

I'm going to close this issue again, as it seems that the alteration to the `_check_spatial_type` function is just what was needed. Thanks so much!

**Comment by adrien-berchet** [comment]
Ok, perfect! I am going to push a new release then.
And just for curiosity: do you actually need to set the `impl` attribute when overriding the `load_dialect_impl()` method?

**Comment by ryangooch** [comment]
Good question. I wasn't sure if it was required so I checked the [SQLAlchemy documentation](https://docs.sqlalchemy.org/en/14/core/custom_types.html#sqlalchemy.types.TypeDecorator) for `TypeDecorator`, which says:

> The class-level impl attribute is required, and can reference any TypeEngine class. Alternatively, the load_dialect_impl() method can be used to provide different type classes based on the dialect given; in this case, the impl variable can reference TypeEngine as a placeholder.

That felt self-contradictory, since it stated that it is required, but that there was an alternative option. So I tried to define the class without the `impl` attribute which resulted in an `AssertionError`:

`AssertionError: TypeDecorator implementations require a class-level variable 'impl' which refers to the class of type being decorated`

Looks like it's required after all! I'm still learning the in's and out's of the SQLAlchemy library, so this was good to check out :)

**Comment by adrien-berchet** [comment]
Indeed the doc is quite confusing. I guess the assertion should check that the `impl` attribute is set AND that the `load_dialect_impl` method is not overridden. But I don't know, it might be even more confusing for the user in the end...
Maybe you can create an issue on the SQLAlchemy tracker for this?
