### ISSUE TITLE
Strange tag...

### ISSUE THREAD

**Issue by sbrunner** [geoalchemy/geoalchemy2#348]
https://github.com/geoalchemy/geoalchemy2/releases/tag/10.0.2

Shouldn't be 0.10.2?

**Comment by adrien-berchet** [comment]
oh god... :facepalm: 
Thanks for your report!

**Comment by sbrunner** [comment]
Thnaks :-)

**Comment by adrien-berchet** [comment]
I remove the tag and the release on GitHub but I can't remove it from pypi, I think only @elemoine can do it. I am going to try to contact him to fix this.
