### ISSUE TITLE
RecoverGeometryColumn instead of AddGeometryColumn

### ISSUE THREAD

**Issue by SaelKimberly** [geoalchemy/geoalchemy2#350]
Hello,  I am a new to the Geoalchemy community, but have some experience with using Spatialite with just default sqlite.

My problem is that I can't create a Check constraint on three geometric columns and one regular (TEXT).

An example of how it worked before, via RecoverGeometryColumn:

```
drop table if exists abc;
--There we create a regular columns with dummy type GEOMETRY (actually - BLOB, I suppose).
create table abc(a GEOMETRY, b GEOMETRY, c GEOMETRY, d, CHECK((a is null and b is null and c is null) = (d is null)));
--After that, all three columns become actually geometry ones:
select RecoverGeometryColumn('abc', 'a', -1, 'MULTIPOLYGON', 2);
select RecoverGeometryColumn('abc', 'b', -1, 'MULTILINESTRING', 2);
select RecoverGeometryColumn('abc', 'c', -1, 'MULTIPOINT', 2);
```

Maybe, also, it can be helpful for working with other constraints on geometry, and for saving the order of columns in table...

**Comment by adrien-berchet** [comment]
Hi @SaelKimberly 
Thank you for your report.
TBH I don't know much about spatialite but I don't get why you can not just use the `AddGeometryColumn` in your case?
Also, did you try to set `management=False`? I think it should do something very close to what you described: create a dummy column with `GEOMETRY` type that you can then update using `RecoverGeometryColumn`.

Anyway, could you provide an example of code so we can speak about it in details? And so I can see what you tried and what error you get?
I will try to work on this tonight or tomorrow.

**Comment by SaelKimberly** [comment]
Thank you for your reply. I will try to describe the issue in as much detail as possible.

1. I'll try to create table in such manner (ORM):

```
Base = declarative_base()
class kpt_global(Base):
    __tablename__ = 'kpt_global'
    __table_args__ = (
        CheckConstraint('(geom_pg is null and geom_ln is null and geom_pt is null) = (geom_sk is null)', 'check_geom_sk'),)

    objectid = Column('objectid', Text, nullable=False,
                      unique=True, primary_key=True)
    # Some columns omitted...
    # force_local() function - True, if app config is set to Spatialite usage.
    geom_pg = Column('geom_pg', Geometry(
        'MULTIPOLYGON', managed=force_local()))
    geom_ln = Column('geom_ln', Geometry(
        'MULTILINESTRING', managed=force_local()))
    geom_pt = Column('geom_pt', Geometry(
        'MULTIPOINT', managed=force_local()))

    geom_sk = Column('geom_sk', Text)
    # Some columns omitted...
```
2. When connecting, I use event for initialize Spatialite db:

```
from aiosqlite.core import Connection as loc_conn
# ...
                engine = create_async_engine(conn)
                @event.listens_for(engine.sync_engine, "engine_connect")
                @sync_as_async
                async def _(conn, _):
                    raw: loc_conn = conn.connection.driver_connection
                    # Attempt to load spatial extensions (if not exists)
                    await raw.enable_load_extension(True)
                    try:
                        await raw.load_extension('mod_spatialite')
                    except Exception:
                        raise FileNotFoundError(
                            'Cannot load extension "mod_spatialite.dll"')
                    await raw.enable_load_extension(False)
                    try:
                        # Shouldn't be failed, when spatial metadata already initialized.
                        await raw.execute('select 1 from spatial_ref_sys limit 1;')
                    except OperationalError:
                        await raw.execute('select InitSpatialMetaData(1);')
                        await raw.commit()
```
3. When I call to `Base.metadata.create_all`, and use Spatialite, an Exception always occures: 'No such column geom_pg'. It's because these columns actually wasn't created with the table (see P.P.S for details)

4. If I set managed to False, when use Spatialite, another Exception occures: 'near "'MULTIPOLYGON'": syntax error'.

It's because sqlite not supports PostGIS geometry column definition:
`create table abc(a geometry('MULTIPOLYGON', -1)); -- When this is wrong in SQLite...`
`create table abc(a GEOMETRY); -- This will be accepted`

Just take a look to the **geoalchemy2.types:156** - this is why I cannot create dummy columns...
P.S. Also, Spatial Index in Spatialite will not be automatically dropped, when the table is dropped, as if we use PostGIS.
P.P.S. In SQLite, there is no way to add CheckConstraint to already created table, so using AddGeometryColumn actually make it impossible :D

**Comment by adrien-berchet** [comment]
Thank you for these details.
I did not know your PS and PPS but indeed they probably prevent you to do what you want.
As far as I can see from you description, we should actually always use `RecoverGeometryColumn` instead of `AddGeometryColumn` when using SQLite, isn't it? So the constraints could be defined at the same time as the table, then when the table is created the columns are created with dummy types and the constraints are created, and then in the `after-create` event we call `RecoverGeometryColumn` on these columns. Would that make sense to you?
I will have to study the doc a bit more to be sure but we could change our internal workflow to this.

**Comment by SaelKimberly** [comment]
Thank you again!

Yes, you're right, I think it's really better this way. At one time, I compared the results of the execution of the `RecoverGeometryColumn` and `AddGeometryColumn` functions to make sure that nothing would be broken.

In Spatialite, the result of performing these functions is equivalent (provided that incorrect data is not written to the assumed geometric columns, in the case of `RecoverGeometryColumn`). However, this does not matter in the case when we create a new table - these columns are a priori empty.

The main idea of using `RecoverGeometryColumns` is to avoid changing the schema after creating the table. This will make it easy to avoid the main problems: the management of constraints on columns can be transferred to sqlalchemy, including nullable, and others. It will also allow you to add `CHECK` constraints on columns (which is not possible at the moment). It can also be noted that this way you can keep the order of the columns.

Thus, for `after-create` events, I only "recover" geometric columns and created indexes, and for `before-drop` events, I deleted geometric columns and indexes (drop one virtual table and three real tables after `DisableSpatialIndex`).

Thanks again, I really appreciate your work!

**Comment by SaelKimberly** [comment]
Hi @adrien-berchet 
The changes made in this branch look very promising.
I will definitely test them tomorrow.
It was really very nice to study your solution!

**Comment by SaelKimberly** [comment]
Hello again, @adrien-berchet :)

My tests were also quite successful!
I approve the changes made, and thank you for your work!
I especially want to thank you for the fact that now it is not necessary to write `management=True` for Spatialite :D
