### ISSUE TITLE
Adding SpatiaLite Geometry Columns with Alembic?

### ISSUE THREAD

**Issue by ryangooch** [geoalchemy/geoalchemy2#351]
I encountered this issue when trying to update existing tables to include geospatial columns. If we assume that we have some model for a class as such:

```python
class GeoTable(Base):
    __tablename__ = 'geo_table'
    id = sa.Column(sa.Integer, primary_key=True)
    foo = sa.Column(sa.Float)
```

and we want to add a `Geometry` column to this existing table in an existing database through a migration, we might have an Alembic migration version script like this

```python
[...]
def upgrade():
    op.add_column("geo_table", sa.Column("geom", Geometry("POINT", srid=4326)))

[...]
```

the migration produces the following error upon attempted migration:
```shell
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "POINT": syntax error
[SQL: ALTER TABLE geo_table ADD COLUMN geom geometry(POINT,4326)]
```

I suspect this is a similar issue to that which was addressed in #342, whereby a `sqlalchemy` event handler was needed in order to monitor for changes coming from a `TypeDecorator` class. 

One workaround that occurred to me was to have the migration check the dialect prior to attempting to add the column, then use the `SpatiaLite` function for adding a `Geometry` column directly. However, I'm not sure what to do in the case the column we wish to add to an existing table is defined using the `TypeDecorator` construct.

As always, I appreciate any help, and thanks again for all your work on this fantastic project!

**Comment by adrien-berchet** [comment]
Hello again @ryangooch :)
Indeed we only catch events for table creation, not for table altering, so it's probably due to this. I am not sure an event for this case exists in sqlalchemy, I will have to look in the doc wen I have some time.
For your specific case, if you have a workaround for the `Geometry` type, can't you do the same when `isinstance(col_type.load_dialect_impl(dialect), Geometry) is True`, as we did in #342 ?

**Comment by ryangooch** [comment]
Thanks for the quick response @adrien-berchet ! 

I will look more into both the "alter table"-style event (if there is one) and also I will search for a workaround on the line you describe. In either case, I'll update here what I can find.

**Comment by ryangooch** [comment]
Hello @adrien-berchet! After spending some time at the drawing board, I've come up with a solution to this problem, something that works with custom types, like those we discussed in #342 . The solution involves describing a custom alembic migration operation that can be used in a migration context to add/drop geospatial columns "intelligently". The relevant documentation is here: [Alembic - Operation Plugins](https://alembic.sqlalchemy.org/en/latest/api/operations.html#operation-plugins). Following that example, we can create a couple of classes and functions that check to see what the underlying database dialect is, and issue the appropriate commands based on the DB backend.

I've created an example to share here, in case anyone else needs this sort of functionality in future. It is based on the `HybridGeospatial` custom type class and `GeoTable` database table from #342.

```python
import sqlalchemy as sa
from alembic.operations import Operations, MigrateOperation


@Operations.register_operation("add_geospatial_column")
class AddGeospatialColumn(MigrateOperation):
    """
    Adds a Geospatial Column in an Alembic migration context. This methodology originates from
    https://alembic.sqlalchemy.org/en/latest/api/operations.html#operation-plugins
    """
    def __init__(self, table_name, column_name, column_type, **kw):
        """
        table_name: name of the table in which to add the geospatial column
        column_name: name of the geospatial column
        column_type: GeoAlchemy-style type, or custom type
        kw: keyword arguments to pass to the constructor
        """
        self.table_name = table_name
        self.column_name = column_name
        self.column_type = column_type
        self.kw = kw

    @classmethod
    def add_geospatial_column(cls, operations, table_name, column_name, column_type, **kw):
        """Handle the different situations arising from adding geospatial column to a DB"""

        op = AddGeospatialColumn(table_name, column_name, column_type, **kw)
        return operations.invoke(op)

    def reverse(self):
        """needed in order to support autogenerate"""
        return DropGeospatialColumn(self.table_name, self.column_name, self.column_type)


@Operations.register_operation("drop_geospatial_column")
class DropGeospatialColumn(MigrateOperation):
    """Drops a Geospatial Column in an Alembic migration context"""
    def __init__(self, table_name, column_name, **kw):
        """
        table_name: name of the table in which to add the geospatial column
        column_name: name of the geospatial column
        column_type: GeoAlchemy-style type, or custom type
        kw: keyword arguments to pass to the constructor
        """
        self.table_name = table_name
        self.column_name = column_name
        self.kw = kw

    @classmethod
    def drop_geospatial_column(cls, operations, table_name, column_name, **kw):
        """Handle the different situations arising from dropping geospatial column from a DB"""

        op = DropGeospatialColumn(table_name, column_name, **kw)
        return operations.invoke(op)

    def reverse(self):
        """needed in order to support autogenerate"""
        return AddGeospatialColumn(self.table_name, self.column_name, self.column_type)


@Operations.implementation_for(AddGeospatialColumn)
def add_geospatial_column(operations, operation):
    """
    Handles the actual column addition by checking for the dialect backend and issuing proper
    commands.

    Parameters:
        operations: Operations object from alembic base, defining high level migration operations
        operation: AddGeospatialColumn call, with attributes for table_name, column_name,
            column_type, and optional keywords.
    """

    table_name = operation.table_name
    column_name = operation.column_name

    dialect = operations.get_bind().dialect
    # Will be either geoalchemy2.types.Geography or geoalchemy2.types.Geometry, if using
    # HybridGeospatial custom type
    geospatial_core_type = operation.column_type.load_dialect_impl(dialect)

    if "sqlite" in dialect.name:
        operations.execute(sa.func.AddGeometryColumn(
            table_name,
            column_name,
            geospatial_core_type.srid,
            geospatial_core_type.geometry_type
        ))
    elif "postgresql" in dialect.name:
        operations.add_column(
            table_name,
            sa.Column(
                column_name,
                operation.column_type
            )
        )


@Operations.implementation_for(DropGeospatialColumn)
def drop_geospatial_column(operations, operation):
    """
    Handles the actual column removal by checking for the dialect backend and issuing proper
    commands.
    """

    table_name = operation.table_name
    column_name = operation.column_name

    dialect = operations.get_bind().dialect

    if "sqlite" in dialect.name:
        operations.execute(sa.func.DiscardGeometryColumn(table_name, column_name))
        # this second drop column call is necessary; SpatiaLite was designed for a SQLite that did
        # not support dropping columns from tables at all. DiscardGeometryColumn removes associated
        # metadata and triggers from the DB associated with a geospatial column, without removing
        # the column itself. The next call actually removes the geospatial column, IF the underlying
        # SQLite package version >= 3.35
        operations.drop_column(table_name, column_name)
    elif "postgresql" in dialect.name:
        operations.drop_column(table_name, column_name)
```

Then, the alembic migration version could use the operation plugin as such:

```python
from alembic import op
from some.ddl import HybridGeospatial


def upgrade():
    op.add_geospatial_column(
        table_name="geo_table",
        column_name="geom",
        column_type=HybridGeospatial(
            geometry_type="POINT",
            management=True,
            from_text="ST_GeomFromEWKT"
        )
    )


def downgrade():
    op.drop_geospatial_column(table_name="geo_table", column_name="geom")
```

Now my question for you: Do you think this sort of alembic migration operation plugin should be under the purview of the `GeoAlchemy2` library? Or is this the sort of thing that is out of scope, and up to the user to define and use?

**Comment by adrien-berchet** [comment]
Hey @ryangooch 
Sorry for the delay, this issue is now the next one on my list :)

Thank you very much for your very detailed solution, I will try to study it carefully soon.
As far as I can see at a first look, this issue should indeed be handled on the Alembic side (as you did) because standard `GeoAlchemy2` users should just explicitly call `func.AddGeometryColumn(...)`. So your solution is probably right (though I am quite surprised that so much code is needed for this, but that's an Alembic story).

I created new helpers for alembic in `geoalchemy2.alembic_helpers` so this solution could definitely be added to this file.

**Comment by adrien-berchet** [comment]
Just a question about your solution: does it work for a standard `Geometry` column? Because you call `geospatial_core_type = operation.column_type.load_dialect_impl(dialect)` which should raise an `AttributeError` for `Geometry` type.

**Comment by ryangooch** [comment]
I think that we could do like you did in the `__init__.py` instead, where there's some logic for type checking on the column type.

Spitballing here:

```python
[...]
if isinstance(operation.column_type, Geometry):
    geospatial_core_type = Geometry
elif isinstance(operation.column_type, Geography):
    geospatial_core_type = Geography
else:
    geospatial_core_type = operation.column_type.load_dialect_impl(dialect)
[...]
```

... there's probably a more concise way to do that, but I suspect that sort of flow could work. 

In our case, we wanted to support both sqlite (where we only can use `Geometry`) and postgres (where we would prefer to use `Geography`) so the code above is a bit specific to that use case. However, I don't _think_ that it would be a problem if the user of this wanted only `Geometry` either way.

**Comment by adrien-berchet** [comment]
Hi @ryangooch !
I tried to add your helpers into `geoalchemy2.alembic_helpers` and in the doc in #362 . Could you check that it suits your needs please?

**Comment by adrien-berchet** [comment]
Thank you very much for this work @ryangooch !
