### ISSUE TITLE
Incompatibility with SQLAlchemy master (cannot import name 'with_metaclass')

### ISSUE THREAD

**Issue by auxsvr** [geoalchemy/geoalchemy2#355]
With commit 31acba8ff7c123a20ae308b7f4ab6df3df264b48, SQLAlchemy removed the compatibility code, which makes Geoalchemy2 fail to import with:
> ImportError: cannot import name 'with_metaclass' from 'sqlalchemy.util'

**Comment by adrien-berchet** [comment]
Hi @auxsvr 
I think I fixed this in #357 , please reopen if you still have any issue with this.
