### ISSUE TITLE
Map PostGIS function to multiple Spatialite functions

### ISSUE THREAD

**Issue by iwishiwasaneagle** [geoalchemy/geoalchemy2#377]
In PostGIS we have `ST_Affine(geom, a, b, d, e, xoff, yoff)` but in Spatialite this functionality is split across 2 functions: `ATM_Transform( geom , affine_matrix )`, and `ATM_Create(a, b, d, e, xoff, yoff)`. How would I go about doing something similar to [this](https://geoalchemy-2.readthedocs.io/en/latest/gallery/test_specific_compilation.html#sphx-glr-gallery-test-specific-compilation-py) using GeoAlchemy2? As far as I can tell, I can't split up and compile individually the `compiled = compiler.process(element.clauses, **kw)`.

**Comment by adrien-berchet** [comment]
Hi @iwishiwasaneagle 
I never tried this but as far as I can see you would like to transform
```sql
SELECT ST_AsText(ST_Affine(ST_GeomFromText('Point(1 2)'), 1, 2, 3, 4, 0, 0));
```
into
```sql
SELECT ST_AsText(ATM_Transform(ST_GeomFromText('Point(1 2)'), ATM_Create(1, 2, 3, 4, 0, 0)));
```
If that's right, I think you can indeed use something similar to https://geoalchemy-2.readthedocs.io/en/latest/gallery/test_specific_compilation.html#sphx-glr-gallery-test-specific-compilation-py. I didn't try but I guess it could be something like this?
```python
def _compile_affine_sqlite(element, compiler, **kw):
    """Compile the element for the SQLite dialect."""
    compiled = compiler.process(element.clauses, **kw)
    affine_params = list(element.clauses)

    element.identifier = "ATM_Transform"

    atm_create_clause = func.ATM_Create(*[i.value for i in affine_params[1:]])
    element.clauses.clauses = element.clauses.clauses[:1] + [atm_create_clause]
    atm_create_compiled = compiler.process(element.clauses, **kw)
    return '{}({})'.format(element.identifier, atm_create_compiled)

compiles(functions.ST_Affine, 'sqlite')(_compile_affine_sqlite)
```

**Comment by iwishiwasaneagle** [comment]
This looks pretty much  exactly like what I was  looking for! Will update when I get around to  implementing it. Cheers.

**Comment by adrien-berchet** [comment]
Ok, cool!
Cheers

**Comment by iwishiwasaneagle** [comment]
Hi @adrien-berchet, this worked a treat. Thank you so much!

**Comment by adrien-berchet** [comment]
Great, glad to know!
