### ISSUE TITLE
'No function matchs the given name and  argument types ...' errors due to incorrect return type of 'geometry', instead of 'geography'

### ISSUE THREAD

**Issue by huonw** [geoalchemy/geoalchemy2#379]
Thanks for geoalchemy2, it's letting us work quickly!

I notice that there's a bunch of PostGIS functions that are annotated with their return type, however some of these are incorrect for overloaded functions like `ST_Centroid` https://postgis.net/docs/ST_Centroid.html:

```
geometry ST_Centroid(geometry g1);

geography ST_Centroid(geography g1, boolean use_spheroid=true);
``` 

Geoalchemy2 annotates the return type as geometry, and thus SQLAlchemy inserts the wrong conversion (`ST_AsEWKB`, instead of `ST_AsBinary`), and the query is rejected by PostgreSQL. Reproducer with both a workaround using `type_coerce (`GOOD`) and the problematic code (`BUG`):

```python
from geoalchemy2 import Geography
import sqlalchemy as sa

url = sa.engine.url.URL.create(
    "postgresql",
    username="postgres",
    password="postgres",
    host="localhost",
    port=5431,
    database="postgres",
)
engine = sa.create_engine(url, echo=True)
engine.execute(sa.text("CREATE EXTENSION IF NOT EXISTS postgis"))

polygon = sa.cast("POLYGON((0 0,1 0,0 1,0 0))", Geography("POLYGON"))

# GOOD:
result = engine.execute(
    sa.select(sa.type_coerce(sa.func.ST_Centroid(polygon), Geography("POINT")))
)

# BUG
engine.execute(
    sa.select(sa.func.ST_Centroid(polygon))
)

```

The relevant output for `GOOD` is:

```
2022-06-01 15:30:20,278 INFO sqlalchemy.engine.Engine SELECT ST_AsBinary(ST_Centroid(CAST(ST_GeogFromText(%(param_1)s) AS geography(POLYGON,-1)))) AS "ST_Centroid_1"
2022-06-01 15:30:20,278 INFO sqlalchemy.engine.Engine [no key 0.00006s] {'param_1': 'POLYGON((0 0,1 0,0 1,0 0))'}
```

And for `BUG`:

```
2022-06-01 15:30:20,485 INFO sqlalchemy.engine.Engine SELECT ST_AsEWKB(ST_Centroid(CAST(ST_GeogFromText(%(param_1)s) AS geography(POLYGON,-1)))) AS "ST_Centroid_1"
2022-06-01 15:30:20,485 INFO sqlalchemy.engine.Engine [no key 0.00034s] {'param_1': 'POLYGON((0 0,1 0,0 1,0 0))'}
2022-06-01 15:30:20,537 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "/Users/huon/tmp/geoalchemy-learning/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/Users/huon/tmp/geoalchemy-learning/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: function st_asewkb(geography) does not exist
LINE 1: SELECT ST_AsEWKB(ST_Centroid(CAST(ST_GeogFromText('POLYGON((...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:
...
```

Full requirements:
```
geoalchemy2==0.11.1
greenlet==1.1.2
packaging==21.3
psycopg2-binary==2.9.3
pyparsing==3.0.9
shapely==1.8.2
sqlalchemy==1.4.36
```

**Comment by huonw** [comment]
Ah, cool, I hadn't realised that trick, thanks for the tip! (And thanks for the quick response 😄 )

**Comment by adrien-berchet** [comment]
You're welcome :-)

**Comment by huonw** [comment]
Nice, thanks @adrien-berchet for the function documentation!

I noticed that SQLAlchemy will automatically compute and implicitly override the `type_` argument for some functions like `min` or `array_agg` where the type depends on the input:
https://github.com/sqlalchemy/sqlalchemy/blob/ad86d32f7fbd1c6deda8ff3bebe0595c0f2986cc/lib/sqlalchemy/sql/functions.py#L1189-L1198

Would you consider a patch adds support for doing this in geoalchemy2 also?

I'm interested in contributing this, although I'm currently busy with a project deadline. I'll hopefully have more breathing space to contribute such a thing in the next month or two. I thought I'd ask before I spend any effort trying to understand how the code works 😄

**Comment by adrien-berchet** [comment]
> Nice, thanks @adrien-berchet for the function documentation!

You're welcome!

> I noticed that SQLAlchemy will automatically compute and implicitly override the `type_` argument for some functions like `min` or `array_agg` where the type depends on the input: https://github.com/sqlalchemy/sqlalchemy/blob/ad86d32f7fbd1c6deda8ff3bebe0595c0f2986cc/lib/sqlalchemy/sql/functions.py#L1189-L1198

Very interesting, I guess we could add such feature. But we have to be careful because some functions do not return the same type as the input one (e.g. `ST_PixelAsPolygon` is applied to a `Raster` and returns a `Geometry`), so we have to handle this case.

> Would you consider a patch adds support for doing this in geoalchemy2 also?
> 
> I'm interested in contributing this, although I'm currently busy with a project deadline. I'll hopefully have more breathing space to contribute such a thing in the next month or two. I thought I'd ask before I spend any effort trying to understand how the code works smile

As you could see I don't have much time for this project either and I am basically the only maintainer now, so any help on this project is welcome! :blush:
