### ISSUE TITLE
Why is GA2 adding `ST_AsEWKB` when querying for a `geometry`

### ISSUE THREAD

**Issue by iwishiwasaneagle** [geoalchemy/geoalchemy2#384]
I have a ORM model `Trial` as
```python
class Trial(_BaseModel):
    __tablename__ = "trial"
    id = Column(Integer, primary_key=True)
    coords = Column(Geometry("LINESTRING", 27700))
```
And when I try to query for it,  I end up with
```python
print(sqlalchemy.select(Trial.coords))
# SELECT ST_AsEWKB(trial.coords) AS coords 
# FROM trial
```

### Expected Behaviour
When I query for a geometry, I would like a geometry as shown  in t he screenshot from within pgadmin4
![image](https://user-images.githubusercontent.com/12383029/172579115-f8edac04-c6fe-45be-b8c3-b3d8dae598de.png)

### Actual Behaviour
When I query for the geometry, the query is compiled to return a EWKB which confuses QGIS and other programs. 
![image](https://user-images.githubusercontent.com/12383029/172579405-d351c2fd-4b4b-4541-9f7e-759f7d537779.png)

**Comment by iwishiwasaneagle** [comment]
Also, note that adding `ST_GeomFromEWKB` doesn't resolve anything as the  `ST_FromEWKB`  must  be  getting add after the fact. 

```python
print(sqlalchemy.select(func.ST_GeomFromEWKB(Trial.coords)))
# SELECT ST_AsEWKB(ST_GeomFromEWKB(trial.coords)) AS "ST_GeomFromEWKB_1" 
# FROM trial
```

**Comment by iwishiwasaneagle** [comment]
Okay having a  deeper look I guess this helps when working with the GA2 environment. Is it possible to turn this off though for usage outside of python, like the aformentioned QGIS. I'd prefer creating views like this rather than manually crafting them.

**Comment by iwishiwasaneagle** [comment]
@adrien-berchet Oh wow yes that's exactly what I was looking for. Thank you so much!

**Comment by adrien-berchet** [comment]
Ah perfect, you're welcome :)
