### ISSUE TITLE
`include_object` missing since 0.12 - Breaks Alembic migrations

### ISSUE THREAD

**Issue by Timusan** [geoalchemy/geoalchemy2#387]
In previous versions of Geoalchemy we had to import `include_object` and add it to our context in the Alembic setup:

```
    context.configure(
        url=get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_item=render_item,
        include_object=include_object,
    )
```

This was needed so that Alembic would not try to drop and recreate PostGIS tables.
Did I miss some change from 0.11.1 to 0.12?

**Comment by adrien-berchet** [comment]
Hi @Timusan !
Thank you for your report. Indeed I removed it at some point when I was fixing all this Alembic mess and I forgot to revert it (and update it), sorry about that. Could you try the branch of #388 on your use case please?

**Comment by Timusan** [comment]
Sorry for the late reply. I can confirm that your branch in #338 fixes the issue! 🎉

**Comment by adrien-berchet** [comment]
No problem, thank you very much for testing, I will merge this a release a new version.
