### ISSUE TITLE
Support for  `SQLAlchemy>=1.4`

### ISSUE THREAD

**Issue by henshalb** [geoalchemy/geoalchemy2#399]
```ERROR: geoalchemy2 0.12.3 has requirement SQLAlchemy>=1.4, but you'll have sqlalchemy 1.3.24 which is incompatible.```

**Comment by adrien-berchet** [comment]
Hi @henshalb 
Could you provide a little more context please?
Do you need `GeoAlchemy2` to be compatible with `SQLAlchemy < 1.4`? I tried this #400 but I am not a fan of releasing something that is only partially working this some requirements (for example Alembic helpers and the `to_metadata()` method will not work for `SQLAlchemy < 1.4`)...

**Comment by adrien-berchet** [comment]
Yeah `pip` is not always able to resolve all dependency conflicts during installation, depending on the complexity of your dependency tree.
