### ISSUE TITLE
Alembic migration create index after version bumb.

### ISSUE THREAD

**Issue by gh-tsc** [geoalchemy/geoalchemy2#408]
Having the following table define in Alembic using Geoalchemy2 version 12.0.3 worked, but it fails in version 12.0.5
```
op.create_table(
        "tbl_graph_vertices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "box",
            Box2D(name="box2d"),
            nullable=False
        )
)
```
Error:
`
ERROR:  data type box2d has no default operator class for access method "gist"
HINT:  You must specify an operator class for the index or define a default operator class for the data type.
SQL state: 42704
`
So it seems to be trying to create a spatial index that is wasn't before.

**Comment by adrien-berchet** [comment]
Hi @gh-tsc 
I see that you closed the issue right after writing it. Is it because it actually works or it is a miss click or whatever? It's just to know if I should investigate or not.
Thanks

**Comment by gh-tsc** [comment]
I closed it because I realized that the Box2D was a class defined in our code-base and not from Geoalchemy2. So the error is probably not due to Geoalchemy.

**Comment by adrien-berchet** [comment]
Ah ok ok.
I am not going to investigate then, but feel free to reopen if you need help to fix this.
