### ISSUE TITLE
Incorrect label generated for geo columns in RETURNING clause

### ISSUE THREAD

**Issue by jerluc** [geoalchemy/geoalchemy2#409]
I'm seeing some breaking behaviors when using geoalchemy2 in combination with SQLAlchemy 1.4.21+ as it relates to the wrapping of columns with PostGIS conversion functions.

Given the code below:

```python
from geoalchemy2.types import Geometry
from sqlalchemy import Table, Column, MetaData, Text


class RawGeometry(Geometry):
    def column_expression(self, col: Column):
        return col


md = MetaData()
MyTable = Table(
    "my_table",
    md,
    Column("name", Text),
    # Just adding a sanity check here that uses a "raw" geometry column per the docs
    Column("raw_geometry", RawGeometry(srid=4326)),
    Column("geometry", Geometry(srid=4326)),
)


q = (
    MyTable.insert()
    .values(
        {"name": "test", "raw_geometry": "Doesn't matter", "geometry": "Doesn't matter"}
    )
    .returning(MyTable)
)

print(q)
```

When running using geoalchemy2 @ v0.12.5 and SQLAlchemy @ v1.4.20, I get the following output:

```
INSERT INTO my_table (name, raw_geometry, geometry) VALUES (:name, ST_GeomFromEWKT(:raw_geometry), ST_GeomFromEWKT(:geometry))
RETURNING my_table.name, my_table.raw_geometry, ST_AsEWKB(my_table.geometry) AS geometry
```

Note how the `ST_AsEWKB(my_table.geometry)` is correctly labeled with `geometry` in the `RETURNING` clause.

However, when running using geoalchemy2 @ v0.12.5 and SQLAlchemy @ v1.4.21, I get the following output:

```
INSERT INTO my_table (name, raw_geometry, geometry) VALUES (:name, ST_GeomFromEWKT(:raw_geometry), ST_GeomFromEWKT(:geometry))
RETURNING my_table.name, my_table.raw_geometry, ST_AsEWKB(my_table.geometry) AS geometry_1
```

Note how instead here the `ST_AsEWKB(my_table.geometry)` is incorrectly labeled with `geometry_1` in the `RETURNING` clause.

Has anyone else run into this problem? AFAICT this only happens in a `RETURNING` clause, as doing something like `print(MyTable.select())` shows the same correctly-labeled `geometry` column across both versions.

**Comment by adrien-berchet** [comment]
Hi @jerluc 
Thanks for this accurate report!
I am able to reproduce this behavior but I am not sure it is a real issue? Do you have an example where this new label results in a wrong query?

**Comment by jerluc** [comment]
No problem @adrien-berchet, glad you were able to reproduce (that means I'm not crazy :laughing:).

The query itself is problematic only as it pertains to the resulting rows when executing this query via SQLAlchemy. With only a couple of minor modifications to the previous example to illustrate the end-to-end problem:

```python
from geoalchemy2.types import Geometry
from sqlalchemy import Table, Column, MetaData, Text, create_engine


class RawGeometry(Geometry):
    def column_expression(self, col: Column):
        return col


md = MetaData()
MyTable = Table(
    "my_table",
    md,
    Column("name", Text),
    # Just adding a sanity check here that uses a "raw" geometry column per the docs
    Column("raw_geometry", RawGeometry(srid=4)),
    Column("geometry", Geometry(srid=4)),
)


engine = create_engine("postgresql://XXX:XXX@XXX/XXX")
md.create_all(engine)


q = (
    MyTable.insert()
    .values(
        {
            "name": "test",
            # Just some random EWKB for testing
            "raw_geometry": "01010000200400000000000000000000000000000000000000",
            "geometry": "01010000200400000000000000000000000000000000000000",
        }
    )
    .returning(MyTable)
)

with engine.connect() as conn:
    result = conn.execute(q)
    for row in result:
        print(row["raw_geometry"])  # This still works because the value is not wrapped
        print(row["geometry"])      # This used to work, but is broken starting with SQLAlchemy v1.4.21
```


The full dictionary value of `row` starting in SQLAlchemy v1.4.21 looks like this:

```
{'name': 'test', 'raw_geometry': <WKBElement at 0x7f011052e2e0; 01010000200400000000000000000000000000000000000000>, 'geometry_1': <WKBElement at 0x7f011052e2b0; 01010000200400000000000000000000000000000000000000>}
```

Since the query generated includes `AS geometry_1` starting in SQLAlchemy v1.4.21, this creates unexpected behavior since the wrapping to convert geometries to/from different formats has been mostly "transparent" up until recently. In fact, I only ran into this when I started seeing some failed tests coming from routine dependency maintenance in a codebase of mine, as my code was expecting that a column named `geometry` would come back with the same name.

As a starter, I'd love to learn a bit more about where the label is being generated to begin with in geoalchemy2. From what I can tell, I think the value wrapping is being done deep inside of `geoalchemy2.types._GISType` around [here](https://github.com/geoalchemy/geoalchemy2/blob/master/geoalchemy2/types.py#L151-L165). Is this correct? Or is there somewhere else I should be looking at to find the source of the label?

**Comment by adrien-berchet** [comment]
Ah yeah ok, thanks for the complete example.

I updated your example to reproduce the same behavior with `Text` columns (I tried using a TypeDecorator and inheriting from `Geometry` directly to check that they both give the same result):
```python
from geoalchemy2.types import Geometry
from sqlalchemy import Table, Column, MetaData, Text, Integer
from sqlalchemy.types import TypeDecorator
from sqlalchemy.sql import func

class RawGeometry(Geometry):
    def column_expression(self, col: Column):
        return col

class SpecialText(TypeDecorator):
    impl = Text

    cache_ok = False

    def column_expression(self, col: Column):
        return col.cast(Integer)

md = MetaData()
MyTable = Table(
    "my_table",
    md,
    Column("name", Text),
    # Just adding a sanity check here that uses a "raw" geometry column per the docs
    Column("raw_geometry", RawGeometry(srid=4326, geometry_type="POINT")),
    Column("geometry", Geometry(srid=4326, geometry_type="POINT")),
    # Same with TEXT columns
    Column("a_text", Text),
    Column("a_special_text", SpecialText),
)

q = (
    MyTable.insert()
    .values(
        {
            "name": "test",
            "raw_geometry": "EPSG=4326;POINT(0 0)",
            "geometry": "EPSG=4326;POINT(0 0)",
            "a_text": "foo",
            "a_special_text": "bar",
        }
    )
    .returning(MyTable)
)

print(q)
```

This issue starts from the commit `673ca806b323f47ef7064dd64ffc98240818b930` of SQLAlchemy, in which labeling was updated. So it's either a bug on their side, either our way of updating the `column_expression` that is no more compatible with SQLAlchemy. @zzzeek do you have any idea on this?

**Comment by zzzeek** [comment]
it's not being consistent with select(), which in 1.4/2.0 is not anon-labeling the expression so I should see if it can be fixed, but it might be 2.0 only.

though if you are in 1.4 I would not use that syntax, assuming you are running it through Session.execute() as it will do something completely different in 2.0.

**Comment by zzzeek** [comment]
that is, use `insert()..returning(MyEntity.col.label('foo'))` for now

**Comment by jerluc** [comment]
> I updated your example to reproduce the same behavior with Text columns (I tried using a TypeDecorator and inheriting from Geometry directly to check that they both give the same result):

@adrien-berchet Heh, I just tried the exact same thing too! After some preliminary debugging, I found myself tracing through [this section](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/sql/compiler.py#L3676-L3695) of `sqlalchemy.sql.compiler`. In particular, this part of the compiler code seems to want to treat user-defined types the same as any normal column expression coming back in a `RETURNING` clause.

> that is, use `insert()..returning(MyEntity.col.label('foo'))` for now

@zzzeek that's certainly reasonable for the time being. I have a possible patch that I could send your way via sqlalchemy/sqlalchemy#8770 if that's a better place to track?

**Comment by zzzeek** [comment]
oh you mean to fix the labeling issue?  OK....that stuff is pretty intricate and highly interconnected with other systems and likely has some differences between 2.0 / 1.4, so....sure I can look.  but it might be more involved than a small fix (or maybe not)
