### ISSUE TITLE
Adding Geopackage support

### ISSUE THREAD

**Issue by caspervdw** [geoalchemy/geoalchemy2#410]
Hi @adrien-berchet , first of all, thanks for maintaining this very useful package. We use it intensively to manage our spatialite files.

Recently I investigated whether we could also interface geopackage files with sqlalchemy + geoalchemy. After some tinkering I found that by calling `SELECT EnableGpkgAmphibiousMode()`, you can actually use geoalchemy as-is to use the ORM to read/write in existing geopackage files. Apparently the spatialite driver has support for geopackage (see https://www.gaia-gis.it/gaia-sins/spatialite-sql-5.0.1.html#p16gpkg)

See here for my implementation: https://github.com/nens/threedi-modelchecker/blob/1eca28ca8854d68df1f4fa136903ce15ea0d9701/threedi_modelchecker/threedi_database.py#L64

As geopackage is quite a common format nowadays, I think it might be interesting for geoalchemy to make this a fully supported option. Stuff that I can see that would need attention:

- discerning geopackage and spatialite dialects and calling the `EnableGpkgAmphibiousMode()`
- inspecting geometry columns and indexes 
- adding / removing geometry columns 
- adding / removing spatial indexes

Please let me know what you think about this. I also might be able to help out here in implementing or testing.

**Comment by adrien-berchet** [comment]
Hi @caspervdw 
That's a great idea! Thanks for introducing me to this feature, I didn't know that.
I think we should solve #395 first so then we can add this new feature in the appropriate module. I will try to work on it soon so then we can work on what you propose.

**Comment by adrien-berchet** [comment]
Hey
I took some time to reorganize the code in #414, so the dialects-specific stuffs are separated. So now we can add support for GeoPackage into `geoalchemy2.dialects.sqlite`. I will not have time to work on this before the end of the year (at least) but if anyone is willing to start a PR on this topic I will be glad to review it and help.

**Comment by adrien-berchet** [comment]
Hi @caspervdw 
Sure, any help is always welcome :)
I will send you an email to speak about this soon.

**Comment by adrien-berchet** [comment]
Solved by #456
