### ISSUE TITLE
Remove warning about srid not being enforced when geometry_type is None

### ISSUE THREAD

**Issue by jwkaltz** [geoalchemy/geoalchemy2#417]
I think there should be no warning about srid not being enforced when geometry_type is None, 
I think these 2 lines should be removed:
https://github.com/geoalchemy/geoalchemy2/blob/3337e5e7580a80bb500814fa1f2ef3a32f317673/geoalchemy2/types.py#L247-L248

If there is no geometry, it is obvious that srid is not enforced. The warnings pollute the output, for example when running pytest (the warnings can be suppressed in pytest, but it would be clearer if they were not output at all).

**Comment by adrien-berchet** [comment]
Hi @jwkaltz 
Thanks for your report!
You're right, these warnings do not make any sense for the Raster type. Nevertheless, it does not make sense to provide `geometry_type=None` and a specific SRID for Geometry and Geography types, so I would prefer to keep the warning in this case. Is it enough for you? If not, could you give me some detail about which case these warnings bother you?

**Comment by jwkaltz** [comment]
Thanks for the explanation @adrien-berchet , I found the missing test data in our case which lead to this warning. For me it's OK to proceed as you propose.

**Comment by adrien-berchet** [comment]
Ok, cool, thanks for your feedback!
