### ISSUE TITLE
SQLAlchemy event handlers are too aggressive

### ISSUE THREAD

**Issue by cpcloud** [geoalchemy/geoalchemy2#420]
When [updating](https://github.com/ibis-project/ibis/pull/5296) our `geoalchemy2` dependency to the latest version over in [the ibis project](https://github.com/ibis-project/ibis), we start to see [CI test failures](https://github.com/ibis-project/ibis/actions/runs/3986865996/jobs/6835952644#step:14:1363).

The [important bit](https://github.com/ibis-project/ibis/actions/runs/3986865996/jobs/6835952644#step:14:1427) shows that geoalchemy2 is now registering global event handlers for various DDL operations at import time and those handlers are enforcing a particular dialect.

This means that a user cannot do the following:

1. install `geoalchemy2`
2. use a dialect that doesn't support geometry/geography columns (e.g., `mysql`)
3. run a SQLAlchemy DDL operation using that dialect

It doesn't seem like these handlers are actually doing anything *except* enforcing the dialect, so perhaps they should be removed.

**Comment by adrien-berchet** [comment]
Hi @cpcloud 
Indeed, I forgot to port this update from a branch in which I fixed this... Sorry about that :facepalm:
#421 should solve this issue, could you test this branch with your code to be sure it solves all you need?
Thanks for your report!

**Comment by cpcloud** [comment]
Hey, no worries! Thanks for the quick fix. I'm testing now!

**Comment by cpcloud** [comment]
This fixes the issue, thanks again!

**Comment by adrien-berchet** [comment]
The `0.13.1` version that should fix this is published on Pypi.
