### ISSUE TITLE
Autogeneration doesn't work after adding helpers

### ISSUE THREAD

**Issue by rednaks** [geoalchemy/geoalchemy2#445]
After adding all the suggested helpers in the documentation, I am unable to autogerate revisions anymore, I get this error: 
```
  File "...venv/lib/python3.11/site-packages/geoalchemy2/alembic_helpers.py", line 452, in create_geo_table
    new_op = CreateGeospatialTableOp(
             ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CreateTableOp.__init__() takes 3 positional arguments but 6 were given
```

is it related to  this issue ?  #406

**Comment by adrien-berchet** [comment]
Hi @rednaks ,
Could you tell me which versions you use for the followings please?
* Python
* GeoAlchemy2
* SQLAlchemy
* Alembic

**Comment by adrien-berchet** [comment]
It is indeed failing with `alembic>=1.11`. For now I suggest you to use `alembic<1.11`, I will try to fix this but I don't have much time for now.

**Comment by adrien-berchet** [comment]
Could you test the new release `0.13.3` please? It is supposed to fix this issue.

**Comment by rednaks** [comment]
> Hi @rednaks , Could you tell me which versions you use for the followings please?
> 
>     * Python
> 
>     * GeoAlchemy2
> 
>     * SQLAlchemy
> 
>     * Alembic

sorry for the late reply, here iare my versions: 
```
pythnon= "3.11"
sqlalchemy = "^2.0.13"
alembic = "^1.11.0"
geoalchemy2 = "^0.13.2"
```

I will test the suggested versions

**Comment by rednaks** [comment]
hello again, so the upgrade fixes the autogenerate issues, but now I cant apply the migrations I created using (`alembic upgrade head`) 

I get this error:

```
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table state because extension postgis_tiger_geocoder requires it
HINT:  You can drop extension postgis_tiger_geocoder instead.
```

it looks like it's trying to drop indexes ... (it's the first migration btw)

**Comment by adrien-berchet** [comment]
Is this error with `Alembic==1.11` and `GeoAlchemy2==0.13.3`?
Did you ever manage to make it work with older versions?

As far as I can see, your error comes from a dependency between a table that should be dropped and the extension `postgis_tiger_geocoder`. I don't think the `GeoAlchemy2` helpers for `Alemnbic` has anything to do with this extension, so at first glance I think it's more related to Alembic but it's hard to say. If you can send the Alembic environment and the generated migration script it would be simpler. But it might take some time for me to study it and find a solution...

**Comment by adrien-berchet** [comment]
Ah ok, I see, thanks for these details. Glad to know it works now.
So it seems this issue is solved so I close it but don't hesitate to reopen if you need.
