### ISSUE TITLE
How do I install it in an offline environment?

### ISSUE THREAD

**Issue by D-Ayden** [geoalchemy/geoalchemy2#450]
I used pip to download it.
```cmd
pip dowload geoalchemy2 -d mypkg
```

when I install it
```cmd
pip install geoalchemy2 --find-links=mypkg --on-index
```
There was a error
```cmd
ERROR: Could not fina a version that satisfies the requirement GeoAlchemy2 (from version: none)  
ERROR: No matching distribution found for GeoAlchemy2
```

After I changed the file "GeoAlchemy-0.7.2.tar.gz" to "GeoAlchemy2-0.7.2.tar.gz", I can install it.
but there is a new error when I use it on my code.
```cmd
ImportError: to_postgis() requires geoalchemy2 package.
```

I found its name in the "site-packages" is "geoalchemy", so I changed "import geoalchemy2" to "import geoalchemy" on line 406 in the file “sql.py”,  and it works.

But I think it's too troublesome to do this, maybe it should be more convenient.

**Comment by adrien-berchet** [comment]
Hi @D-Ayden 
Thanks for this report, it's very surprising. I will try to look at this soon. Or maybe @jjgarrett0 can take a look?

**Comment by adrien-berchet** [comment]
I just had a quick look and these commands seem to work:

* with network connected:
  ```bash
  pip download geoalchemy2 -d mypkg
  ```
* with network disconnected:
  ```bash
  pip install --no-index --find-links=mypkg mypkg/GeoAlchemy2-0.13.3-py3-none-any.whl
  ```

**Comment by D-Ayden** [comment]
> ```batchfile
> Could not fina a version that satisfies the requirement GeoAlchemy
> ```

Thank you for your reply, you're right. I didn't realize that the geoalchemy2 I downloaded was not the lastest version. I just download the lastest version and I successfully installed it.

**Comment by adrien-berchet** [comment]
Ok, great :⁠-⁠)
