### ISSUE TITLE
"no such table: main.idx_{table}_{col}" Exception when writing Spatialite

### ISSUE THREAD

**Issue by Danaozhong** [geoalchemy/geoalchemy2#453]
I am getting an exception when using GeoAlchemy2 to write an Spatialite (SQLite) database file.

My table setup looks as follows:

```
def get_points_table(schema: str) -> Table:
    return Table(
        "points",
        metadata,
        Column("point_id", Integer, primary_key=True),
        Column("position", Geometry("POINTZ", srid=4326, dimension=3, management=True)),
        schema=schema,
        keep_existing=True,
    )
```
Before writing, I create an empty SQLite file as follows:
```
engine = create_engine(f"sqlite:///{filename}", echo=False)
listen(engine, "connect", _load_sqlite_spatialite_extension)
conn = engine.connect()
conn.execute(text("BEGIN;"))
conn.execute(text("SELECT InitSpatialMetaData();"))
conn.execute(text("COMMIT;"))
metadata = MetaData()
get_points_table("")
metadata.create_all(conn)
```

I am using the following code to write data to the table:
```
conn.execute(
    get_points_table("").insert().values(
        point_id=1234,
        position=from_shape(
            Point(p.longitude, p.latitude, p.elevation)
        )))
```
This code fails with the following exception:
```
    conn.execute(
C:\Tools\Python39\lib\site-packages\sqlalchemy\engine\base.py:1414: in execute
    return meth(
C:\Tools\Python39\lib\site-packages\sqlalchemy\sql\elements.py:485: in _execute_on_connection
    return connection._execute_clauseelement(
C:\Tools\Python39\lib\site-packages\sqlalchemy\engine\base.py:1638: in _execute_clauseelement
    ret = self._execute_context(
C:\Tools\Python39\lib\site-packages\sqlalchemy\engine\base.py:1842: in _execute_context
    return self._exec_single_context(
C:\Tools\Python39\lib\site-packages\sqlalchemy\engine\base.py:1983: in _exec_single_context
    self._handle_dbapi_exception(
C:\Tools\Python39\lib\site-packages\sqlalchemy\engine\base.py:2325: in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
C:\Tools\Python39\lib\site-packages\sqlalchemy\engine\base.py:1964: in _exec_single_context
    self.dialect.do_execute(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <sqlalchemy.dialects.sqlite.pysqlite.SQLiteDialect_pysqlite object at 0x0000014AEA5B15B0>
cursor = <sqlite3.Cursor object at 0x0000014AEA5BA570>
statement = 'INSERT INTO points (point_id, position) VALUES (?, GeomFromEWKT(?))'
parameters = (1234, 'SRID=-1;POINT Z (... .... 10.01)')
context = <sqlalchemy.dialects.sqlite.base.SQLiteExecutionContext object at 0x0000014AE9B3BEB0>

    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: main.idx_points_position
E       [SQL: INSERT INTO points (point_id, position) VALUES (?, GeomFromEWKT(?))]
E       [parameters: (1234, 'SRID=-1;POINT Z (... .... 10.01)')]
E       (Background on this error at: https://sqlalche.me/e/20/e3q8)

C:\Tools\Python39\lib\site-packages\sqlalchemy\engine\default.py:747: OperationalError
```
The exception looks similar to what was reported in https://github.com/geoalchemy/geoalchemy2/issues/196.

With a bit of debugging, I found out that the problem originates in the handling of the spatial indices table. I therefore disabled spatial indices by adding `spatial_index=False` to the `Geometry` column:
`Column("position", Geometry("POINTZ", srid=4326, dimension=3, management=True, spatial_index=False)),`

With this change, the code works, and the data gets stored in the SQLite file. Nevertheless, I think it would be good to understand what actually goes wrong.

My system setup is as follows:
- Windows 11
- Python 3.9
- GeoAlchemy2, version 0.13.3
- SQLAlchemy, version 2.0.3
- mod_spatialite `mod_spatialite-5.0.1-win-amd64`

**Comment by adrien-berchet** [comment]
Hi @Danaozhong
Thanks for your report!
Could you please provide a complete example in one piece so we just have to copy/paste it to reproduce your issue please? Also, could you run your code with `echo=True` passed to `create_engine` and post the result here? It will be much easier to understand what's going on with this.
Thanks

**Comment by Danaozhong** [comment]
Sure!
Here is a logfile created with `echo=True`.
[complete_log.txt](https://github.com/geoalchemy/geoalchemy2/files/11766224/complete_log.txt)
A minimum example can be found here: https://github.com/Danaozhong/geoalchemy2-spatialite-example

**Comment by Danaozhong** [comment]
Thank you, it seems that the root cause is indeed the way the SpatiaLite library was compiled.

**Comment by adrien-berchet** [comment]
Ok, great!
I close this issue but don't hesitate to reopen it if you have any other question on this.
