### ISSUE TITLE
0.14.0 broken initialization of WKTElements

### ISSUE THREAD

**Issue by lucaslcode** [geoalchemy/geoalchemy2#462]
```
self = <[AttributeError() raised in repr()] WKTElement object at 0x7f671a2b9280>
data = <POLYGON ((-116.919 33.335, -116.919 33.335, -116.902 33.785, -116.914 33.78...>
srid = 4326, extended = None
    def __init__(self, data, srid=-1, extended=None):
        if extended is None:
>           extended = data.startswith("SRID=")
E           AttributeError: 'Polygon' object has no attribute 'startswith'
/usr/local/lib/python3.8/site-packages/geoalchemy2/elements.py:122: AttributeError
```

**Comment by adrien-berchet** [comment]
Hi @lucaslcode 
Thanks for the report and sorry for the inconvenience.
Could you tell me what is the type of your `Polygon` object please? And if you can provide a Minimal Working Example to reproduce this error it would be nice.

**Comment by adrien-berchet** [comment]
Isn't it a `Shapely` object? If it is you should create your `WKTElement` by passing the wkt form of the geometry object, not the raw object. For example:
```python
obj = shapely.wkt.loads("POLYGON((0 0, 0 1, 1 1, 1 0, 0 0))")
elem = WKTElement(obj.wkt)
```

**Comment by lucaslcode** [comment]
Thank you, it is indeed a shapely polygon. Odd that this line was working before!

**Comment by adrien-berchet** [comment]
Yeah previously it could accept anything that can be cast to a str object while now it must be a `str` object. Nevertheless, we could explicitly try to cast it to `str` in the `WKTElement` constructor to keep the same behavior as before, which I never considered but can be convenient.

**Comment by shuttle1987** [comment]
I ran into this as well due to some buggy code that finally broke with this release, an issue that I think would have been easily spotted in the CI pipeline if this package had type annotations. Is there any interest in adding type annotations into this project?

**Comment by adrien-berchet** [comment]
Sure, that would be nice!
Does anyone have some time to add it? It will be hard for me to find time for this before several weeks. For now I'm just going to open an issue.
