### ISSUE TITLE
Multipolygon with one polygon is forced to be Polygon

### ISSUE THREAD

**Issue by jparta** [geoalchemy/geoalchemy2#466]
I have a field in my model that is marked as type MULTIPOLYGON. This field can sometimes have a geometry which has only one polygon, but most of the time it has multiple. When I load the geometry into a WKBElement with shape.from_shape, a geometry with a single polygon is forced to assume the type Polygon. Is this a limitation of the specifications? Shapely is fine with a Multipolygon with only contains a single polygon.

Do I have to use a GeometryCollection? I would rather keep the restriction afforded by specifying the geometry type as narrowly as possible.

**Comment by jparta** [comment]
I found an error in my code. Sorry for the erroneous issue.

**Comment by adrien-berchet** [comment]
Ok, no problem :)
