### ISSUE TITLE
Add support for Mapped and mapped_column from sqlalchemy 2

### ISSUE THREAD

**Issue by phyk** [geoalchemy/geoalchemy2#470]
In sqlalchemy 2.0, the orm side got updated table specifications. With them, it is possible to use python compatible type hints via the Mapped[<type>] construct. Would it be possible to translate this feature to geoalchemy2?

**Comment by ab5y** [comment]
> In sqlalchemy 2.0, the orm side got updated table specifications. With them, it is possible to use python compatible type hints via the Mapped[] construct. Would it be possible to translate this feature to geoalchemy2?

I am actually trying to use the Geometry type with the Mapped[] construct. Any ideas on how to go about this currently? When I try this:
`gps: Mapped[Geometry('Point')]`

I get the error: `AttributeError: 'Geometry' object has no attribute '__mro__'`

Apologies if this is not the appropriate forum for this.

**Comment by liuhenry** [comment]
The python type geoalchemy2 is returning is `WKBElement`:

```python
class Geo(Base):
    ...
    geom: Mapped[WKBElement] = mapped_column(Geometry("Point"))
```

**Comment by phyk** [comment]
Thanks.
