### ISSUE TITLE
bigquery insert error with geometry field

### ISSUE THREAD

**Issue by mephmanx** [geoalchemy/geoalchemy2#471]
II having a bit of trouble insert data into bigquery using geoalchemy2.  Here is the error:

sqlalchemy.exc.ProgrammingError: (google.cloud.bigquery.dbapi.exceptions.ProgrammingError) 'location:geography(POINT,-1)'
[SQL: INSERT INTO `map_component_poi_data` (`id`, `location`, `data`, `account_id`, `last_update_datetime`) VALUES (%(id:INT64)s, ST_GeogFromText(%(location:geography(POINT,-1))s), %(data:STRING)s, %(account_id:STRING)s, %(last_update_datetime:DATETIME)s)]
[parameters: {'id': 21, 'location': 'LINESTRING (-118.00000000000001 33, -73 40)', 'data': '', 'account_id': '1234', 'last_update_datetime': '2023-08-18 13:57:56'}]
(Background on this error at: https://sqlalche.me/e/14/f405)"

When I run the sql manually in bigquery sql sheet, it works fine.

Here is class:

class POIData():
    __table__ = config.TABLE_NAME
    def to_dict(self):
        return {
            "id": self.id,
            "location": self.location,
            "data": self.data,
            "account_id": self.account_id,
            "last_update_datetime": self.last_update_datetime

Here is how I am inserting:

request_data = request.get_json()
    request_data['id'] = index
    request_data['account_id'] = account_id
    request_data['last_update_datetime'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    request_data['location'] = shape(request_data['location']).wkt
    newRec = orm.POIData(**request_data)
    my_session = Session(engine)
    my_session.add(newRec)
    my_session.commit()
    my_session.flush()
    result = my_session.execute(select(orm.POIData).where(orm.POIData.ID == index)).all()
    my_session.close()

Any assistance would be huge!

**Comment by adrien-berchet** [comment]
Hi @mephmanx !
The BigQuery dialect is a bit specific and it's not natively supported by GeoAlchemy2. I suggest you use https://github.com/googleapis/python-bigquery-sqlalchemy, which provides spatial objects specifically derived from GeoAlchemy2 to make it work with BigQuery.

**Comment by mephmanx** [comment]
Thank you for the reply.  I actually did end up using that and got it to work yesterday.  It's good to know that this lib is still maintained so I will use it for other operations I need to perform.

**Comment by adrien-berchet** [comment]
Ok, great!
