### ISSUE TITLE
[Feature request] Support Python3.12

### ISSUE THREAD

**Issue by nrbnlulu** [geoalchemy/geoalchemy2#486]
### Describe the feature

Support Python 3.12  (If it would be added in the CI it would be great)

### Example Use

...

### Use cases

...

**Comment by adrien-berchet** [comment]
Hi @nrbnlulu 
Indeed, it's time to add it, thanks for raising it :)
I opened #487 to fix this.

**Comment by adrien-berchet** [comment]
Do you need a release for this? There is nothing else since the last one but I can still push it if you need.

**Comment by nrbnlulu** [comment]
Hmm I don't think it is required. Thanks VM.

**Comment by adrien-berchet** [comment]
Ok :⁠-⁠)
