### ISSUE TITLE
insert different format support

### ISSUE THREAD

**Issue by iocast** [geoalchemy/geoalchemy2#66]
Is it also possible to support different GeomFrom\* instead of only ST_GeomFromEWKT when doing a session.add(entity).

Or does some has an idea how to do that?

**Comment by grant-humphries** [comment]
For what it's worth here's how I converted geometries from a shapefile read with `fiona` to `shapely` geometry and then into `geoalchemy2` EWKT format such that they could be bulk inserted with `sqlalchemy`:

```python
import fiona
from shapely.geometry import shape
from geoalchemy2.elements import WKTElement

with fiona.open(shapefile_path) as shapefile:
    epsg = int(shapefile.meta['crs']['init'].split(':')[1])    

    for fid, feat in shapefile.items():
        shapely_geom = shape(feat['geometry'])
        ga2_geom = WKTElement(shapely_geom.wkt, epsg)
```
