### ISSUE TITLE
Automap and geometry objects

### ISSUE THREAD

**Issue by x2b** [geoalchemy/geoalchemy2#82]
Hello all,

I have been giving GeoAlchemy2 a try because I need to work on some existing PostGIS data. I would like to use the _automap_ feature from SqlAlchemy for the relevant tables:

```
from sqlalchemy import *

(connect...)

Base = automap_base()
Base.prepare(engine, reflect=True)
```

Everything seems to work, tables are accessible from `Base.classes`. The problem seems to be that the geometric objects are not recognized correctly, when I query the `geom' column of an element I only get a string looking like this:

```
0101000020E61000007C31BF8EE3432640D80C118843134740
```

I would prefer the actual Polygon/LineString/...
Am I doing something wrong or does the automap feature simply not work correctly with spatial data?

**Comment by elemoine** [comment]
I am closing this. Please reopen if it needs more discussion.
