### ISSUE TITLE
Can't insert from select

### ISSUE THREAD

**Issue by daradib** [geoalchemy/geoalchemy2#85]
Without the Geometry type, I can `INSERT ... SELECT` a geometry column:

```
q = session.query(a.geom)
ins = insert(b).from_select((b.geom,), q)
session.execute(ins)

> str(ins)
'INSERT INTO public.b (geom) SELECT public.a.geom AS public_a_geom \nFROM public.a'
```

With the Geometry type, the `column_expression` method wraps the SELECT with an ST_AsBinary call. ST_AsBinary (WKB, not EWKB) doesn't include the SRID, so the insert fails:

```
DataError: (DataError) Geometry SRID (0) does not match column SRID (4326)
'INSERT INTO public.b (geom) SELECT ST_AsBinary(public.a.geom) AS public_a_geom \nFROM public.a' {}
```

As a workaround, I can call func.ST_AsEWKB, which includes the SRID, in the query. Ideally, if possible, it would be nice to prevent the column expression from unnecessarily wrapping the query.

**Comment by elemoine** [comment]
We now use `ST_AsEWKB`, so that should be fixed.
