### ISSUE TITLE
Attribute ColumnComparator not found.

### ISSUE THREAD

**Issue by tasdomas** [geoalchemy/geoalchemy2#88]
A statement:
from geoalchemy.base import *

raises this exception:
AttributeError: type object 'ColumnProperty' has no attribute 'ColumnComparator'

**Comment by PlutusCN** [comment]
I got this exception too, don't know how to fix, do you know how to fix ? Thanks a lot.

**Comment by karavanjo** [comment]
Was installed SQLAlchemy 0.9.8 and I got this exception. After rolling back to version 0.8.4 for SQLAlchemy error was disappeared.

**Comment by jackha** [comment]
Double karavanjo, this combination seems to work:
GeoAlchemy = 0.7.2
SQLAlchemy = 0.8.4

**Comment by iled** [comment]
Florian at [GIS.SE](http://gis.stackexchange.com/questions/109498/geoalchemy-attributeerror-type-object-columnproperty-has-no-attribute-colum) pointed out that [this PR](https://github.com/geoalchemy/geoalchemy/pull/35/files) seems to address this issue.

For now, jackha combo worked for me.

Btw, shouldn't this issue be posted under [geolalchemy1](https://github.com/geoalchemy/geoalchemy)?

**Comment by elemoine** [comment]
@iled yes.
