### ISSUE TITLE
Full python 3 support

### ISSUE THREAD

**Issue by Jenselme** [geoalchemy/geoalchemy2#96]
I saw on #3 and #21 that python 3 is at least partially supported. The problem was with the shapely library which now fully supports python 3. See https://pypi.python.org/pypi/Shapely/1.5.8 I also see that #86 aims to fix a bug with python 3.

Can you give me an update about python 3 support? I am really interested in the support of python 3. If you need some help to complete the port, please let me know.

**Comment by Jenselme** [comment]
With @tigerfoot, we were able to launch all tests against python 3 and they all pass. We looked into the few lines not covered will be fully compatible with python 3 with #99 (which is an improvement of #86)

**Comment by tigerfoot** [comment]
This can be closed, we got python3 support

**Comment by Jenselme** [comment]
I think it requires an new release with python3 support for this to be closed.

**Comment by Turbo87** [comment]
I agree on that, but unfortunately I don't have the necessary credentials to do that...

**Comment by benasher44** [comment]
@elemoine any updates on when the next version bump will happen to officially include python 3 support?

**Comment by elemoine** [comment]
Sorry for the delay!! I'll look at releasing a new version of GeoAlchemy ASAP.

**Comment by Jenselme** [comment]
Thanks for the release!
